# Databricks notebook source
dbutils.widgets.text("dbx_env","dev")

# COMMAND ----------

dbx_env = dbutils.widgets.get("dbx_env").rstrip()
config_file_name = "tmprodvty-conf.yaml"
config_file = "../../../config/"+dbutils.widgets.get("dbx_env")+"/"+config_file_name
if dbx_env =='qa':
    dbx_env = 'test'
print(f'{config_file=},{dbx_env=}')

# COMMAND ----------

# MAGIC %run  ../../../python/shared/ntb_common_func_and_params $config_file=config_file

# COMMAND ----------

#schema variables
common_configs = read_yaml(config_file)
tmprodvty_catalog = common_configs['schema']['trgt_catalog']
data_quality_catalog = common_configs['schema']['data_quality_catalog']
print(f'{tmprodvty_catalog=}, {data_quality_catalog=} ')

#spark.conf.set('config.data_quality_catalog', data_quality_catalog.lower())
#spark.conf.set('conf.catalog', tmbuscalendar_catalog.lower()) 
#spark.conf.set('dbx_env', dbx_env) 

# COMMAND ----------

database = 'bronze'
control_table = 'cdc_batch_job_control'
job_history_table = 'cdc_batch_job_history'

spark.conf.set('conf.catalog', tmprodvty_catalog)
spark.conf.set('conf.database', database)
spark.conf.set('conf.control_table', control_table)
spark.conf.set('conf.job_history_table', job_history_table)
spark.conf.set('conf.dbx_env', dbx_env)

# COMMAND ----------

tables_to_comment = {
    'production_transaction': 'A production transaction is generated when it is determined that the transaction is eligible to earn or withdraw credits to a worker. An organization & employee or organization may earn credits for different types of production transactions. Credits are earned for activities completed during examination. Credit for a transaction may be withdrawn if it is determined that an examining attorney performed unsatisifactory work, the transaction was generated in error, or various other reasons. Credits may also be withdrawn if an Abandonment is later revived. Examination Office Activity Transactions that may earn credits include First Office Action, Abandonment, Approved for Publication, Allowance on Supplemental Register, Examiners Amendment (Phone Credit Only), Priority Action (Phone Credit only), EA/PA Office Action (Phone Credit only).',

    'productivity_action': 'A productivity action is an event type that when generated by a worker, may earn or withdraw credit to that worker. This table contains action codes and definitions.',

    'worker_time_entry': 'This table contains any bi-weekly pay period time entry for a worker. Includes regular and overtime hours.',

    'production_transaction_errlog': 'ORA error log table that identifies production transactions that were unable to be inserted into the production transaction table and the cause of the error.',

    'cdc_batch_job_control': 'The cdc_batch_job_control table in the bronze schema of the trm_tmbuscalendar_dev catalog is used to control and track the Change Data Capture (CDC) batch jobs. It contains information about the source folder, catalog name, database name, and table name for each job. Additionally, it includes the source database name and source table name, which represent the original data source. The primary keys column stores the primary keys for each table, while the full_load column indicates whether a full load is required. The initial_load_finished column is a boolean value that shows whether the initial load has been completed. This table is essential for managing and monitoring the CDC process in the business system.',

    'cdc_batch_job_history': 'The cdc_batch_job_history table contains information about the history of Change Data Capture (CDC) batch jobs. It stores the file path of the CDC file, the source time of the metadata, the date of the CDC file, and the processing time of the job. This table is significant to the business as it allows tracking and monitoring of CDC batch job activities, providing insights into data changes and updates. The data in this table represents the historical records of CDC batch jobs, enabling analysis and troubleshooting of data synchronization processes.'
}

for table_name, comment in tables_to_comment.items():
    alter_table_query = f"""
    ALTER TABLE {spark.conf.get('conf.catalog')}.{spark.conf.get('conf.database')}.{table_name}
    SET TBLPROPERTIES ('comment' = '{comment}')
    """
    spark.sql(alter_table_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'production_credit_tran_id':'A numeric value that uniquely identifies each instance of a production transaction',
'cfk_object_gid':'The global identifier that supports universal unique identification and reference of any global object',
'cfk_object_type_cd': 'The code that represents an object type',
'fk_generating_prodvty_actn_id':'A numeric value that uniquely identifies each instance of a productivity action',
'fk_corrected_prodvty_actn_id':'Identifies the productivity action that is corrected or withdrawn as a result of the production transaction',
'unit_count_no':'The number of credit units that are awarded for the production credit transaction',
'transaction_effective_dt':'The date and time on which the production transaction occurred and is used to determine the pay period the credits are applied',
'dn_worker_no':'Unique number that identifies a specific employee and identifies worker that generated the production transaction',
'dn_worker_tm_organization_cd':'Identifies the trademark organization in which the worker generated the production transaction',
'dn_worker_role_cd':'Identifies the user role that the worker performed at the time the production transaction was generated',
'cfk_worker_gid':'The global identifier that uniquely identifies the worker that earned the credit/withdrawal',
'cfk_worker_tm_organization_gid':'The global identifier that supports universal unique identification and reference of a trademark organization',
'cfk_worker_user_role_id':'A numeric value that uniquely identifies each instance of a user role',
'dn_contributor_worker_no':'Identifies a worker that contributed to the production transaction',
'dn_contributor_worker_role_cd':'Identifies the user role that the contributing worker performed at the time the production transaction was generated',
'dn_contributor_tm_org_cd':'Identifies the organization in which the contributing worker generated the production transaction',
'cfk_contributor_worker_gid':'The global identifier that uniquely identifies the contributing worker to the production transaction',
'cfk_contributor_user_role_id':'Identifies the user role that the contributing worker performed at the time the production transaction was generated',
'cfk_contributor_tm_org_gid':'The global identifier that supports universal unique identification and reference of a trademark organization',
'cfk_bcr_pay_period_range_name':'Identifies the pay period date range in which the production transaction was generated',
'dn_action_no':'A sequential number assigned to an action during the prosecution of an application',
'priority_in':'The indicator which signals the presence of a priority transaction',
'transaction_ct':'TRAM legacy code that categorizes the transaction as ITU, LIE, PEQ, or PR',
'work_unit_cd':'TRAM legacy code that identifies the transaction work unit',
'lock_control_no':'Number used for lock control',
'create_ts':'Timestamp of when the record was created',
'create_user_id':'User ID of the user who created the record',
'last_mod_ts':'Timestamp of when the record was last modified',
'last_mod_user_id':'User ID of the user who last modified the record',
'subsequent_action_in':'From legacy TMIIBC30 transactions(6321, 6663, 6664) used in productivity reporting',
'delete_in':'Indicator which signals that the data was removed from TRAM ep table'
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='production_transaction', column_name=column, comment=comment)

  spark.sql(column_comment_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'productivity_action_id':'A numeric value that uniquely identifies each instance of a productivity action',
'productivity_action_cd':'The action code that denotes a productivity action',
'sub_action_cd':'A sub action code further describes a productivity action with additional details',
'title_tx':'A short descriptive name to identify the productivity action code',
'lock_control_no':'The integer value for lock control',
'create_ts':'The timestamp when the property was created',
'create_user_id':'The user ID who created the property',
'last_mod_ts':'The timestamp when the property was last modified',
'last_mod_user_id':'The user ID who last modified the property',
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='productivity_action', column_name=column, comment=comment)

  spark.sql(column_comment_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'worker_time_entry_id':'The unique number to identify a worker time entry',
'cfk_pp_range_nm':'The pay period number designator',
'entry_date':'The date and time that the time was entered',
'cfk_worker_gid':'The global identifier that uniquely identifies the worker',
'cfk_user_role_id':'Unique number that identifies a user role',
'cfk_tm_organization_gid':'The global identifier that supports universal unique identification of a trademark organization',
'regular_hours_qt':'The number of regular hours worked in quarter increments',
'overtime_hours_qt':'The number of overtime hours worked in quarter increments',
'fk_task_cd':'The unique code which identifies the task for which the worker has entered time',
'lock_control_no':'The lock control number for the calendar day',
'create_ts':'The timestamp when the calendar day was created',
'create_user_id':'The user ID of the user who created the calendar day',
'last_mod_ts':'The timestamp of the last modification made to the calendar day',
'last_mod_user_id':'The user ID of the user who made the last modification to the calendar day'
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='worker_time_entry', column_name=column, comment=comment)

  spark.sql(column_comment_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'ora_err_number':'ORA error number',
'ora_err_mesg':'ORA error message text',
'ora_err_optyp':'Type of operation I(insert), U(update), D(delete)',
'ora_err_tag':'Error tag text',
'production_credit_tran_id':'A numeric value that uniquely identifies each instance of a production transaction',
'cfk_object_gid':'The global identifier that supports universal unique identification and reference of any global object',
'cfk_object_type_cd': 'The code that represents an object type',
'fk_generating_prodvty_actn_id':'A numeric value that uniquely identifies each instance of a productivity action',
'fk_corrected_prodvty_actn_id':'Identifies the productivity action that is corrected or withdrawn as a result of the production transaction',
'unit_count_no':'The number of credit units that are awarded for the production credit transaction',
'transaction_effective_dt':'The date and time on which the production transaction occurred and is used to determine the pay period the credits are applied',
'dn_worker_no':'Unique number that identifies a specific employee and identifies worker that generated the production transaction',
'dn_worker_tm_organization_cd':'Identifies the trademark organization in which the worker generated the production transaction',
'dn_worker_role_cd':'Identifies the user role that the worker performed at the time the production transaction was generated',
'cfk_worker_gid':'The global identifier that uniquely identifies the worker that earned the credit/withdrawal',
'cfk_worker_tm_organization_gid':'The global identifier that supports universal unique identification and reference of a trademark organization',
'cfk_worker_user_role_id':'A numeric value that uniquely identifies each instance of a user role',
'dn_contributor_worker_no':'Identifies a worker that contributed to the production transaction',
'dn_contributor_worker_role_cd':'Identifies the user role that the contributing worker performed at the time the production transaction was generated',
'dn_contributor_tm_org_cd':'Identifies the organization in which the contributing worker generated the production transaction',
'cfk_contributor_worker_gid':'The global identifier that uniquely identifies the contributing worker to the production transaction',
'cfk_contributor_user_role_id':'Identifies the user role that the contributing worker performed at the time the production transaction was generated',
'cfk_contributor_tm_org_gid':'The global identifier that supports universal unique identification and reference of a trademark organization',
'cfk_bcr_pay_period_range_name':'Identifies the pay period date range in which the production transaction was generated',
'dn_action_no':'A sequential number assigned to an action during the prosecution of an application',
'priority_in':'The indicator which signals the presence of a priority transaction',
'transaction_ct':'TRAM legacy code that categorizes the transaction as ITU, LIE, PEQ, or PR',
'work_unit_cd':'TRAM legacy code that identifies the transaction work unit',
'lock_control_no':'The lock control number for the calendar day',
'create_ts':'The timestamp when the calendar day was created',
'create_user_id':'The user ID of the user who created the calendar day',
'last_mod_ts':'The timestamp of the last modification made to the calendar day',
'last_mod_user_id':'The user ID of the user who made the last modification to the calendar day',
'subsequent_action_in':'From legacy TMIIBC30 transactions(6321, 6663, 6664) used in productivity reporting',
'delete_in':'Indicator which signals that the data was removed from TRAM ep table'
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='production_transaction_errlog', column_name=column, comment=comment)

  spark.sql(column_comment_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'src_folder':'The folder where the source data is stored.',
'catalog_name':'The name of the catalog where the table is located.',
'database_name':'The name of the database where the table is located.',
'table_name':'The name of the table.',
'source_db_name':'The name of the source database.',
'source_table_name':'The name of the source table.',
'primary_keys':'The primary keys of the table.',
'full_load':'Indicates if the table needs to be fully loaded.',
'initial_load_finished':'Indicates if the initial load of the table has finished.',
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='cdc_batch_job_control', column_name=column, comment=comment)

  spark.sql(column_comment_query)

# COMMAND ----------

# Define a dictionary of column comments
column_comments = {
'cdc_file_path':'The file path of the CDC file.',
'meta_src_time':'The source time of the metadata.',
'cdc_file_date':'The date of the CDC file.',
'processing_time':'The processing time of the job.',
}

# Loop through the columns and generate column comment queries
for column, comment in column_comments.items():
  column_comment_query = """
  ALTER TABLE {catalog}.{database}.{table}
  ALTER COLUMN {column_name}
  COMMENT '{comment}'
  """.format(catalog=tmprodvty_catalog, database=database, table='cdc_batch_job_history', column_name=column, comment=comment)

  spark.sql(column_comment_query)
