# Databricks notebook source
dbutils.widgets.text("dbx_env","dev")
dbx_env = dbutils.widgets.get("dbx_env").rstrip()
 
config_file = f"../../config/{dbx_env}/trmreports-conf.yaml"
print(f'{config_file=}')

# COMMAND ----------

# MAGIC %run ../shared/ntb_common_func_and_params $config_file=config_file

# COMMAND ----------

common_configs = read_yaml(config_file)
reporting_catalog = common_configs['schema']['reporting_catalog']
scope = common_configs['secrets']['edw_scope']
reporting_catalog, scope

# COMMAND ----------


join_query = spark.sql(f"""
 With H as (
 SELECT
 EMPLOYEE_NUMBER_VW_SL_HRSA_EM,
 EMP_HIST_EMPLOYEE_NUMBER,
 EMP_HIST_FROM_AGENCY_CODE,
 EMP_HIST_FROM_DEPARTMENT_CODE,
 EMP_HIST_FROM_ORGANIZATION_COD,
 EMP_HIST_NATURE_OF_ACTION_DATE,
 EMP_HIST_ORGANIZATION_CODE,
 EMP_HIST_TO_AGENCY_CODE,
 EMP_HIST_TO_DEPARTMENT_CODE,
 EMP_HIST_TO_NATURE_OF_ACTION_C,
 EMP_HIST_TO_NATURE_OF_ACTION_1,
 EMP_HIST_TO_NATURE_OF_ACTION_D,
 EMP_HIST_TO_ORGANIZATION_CODE,
 NATURE_OF_ACTION_DESCRIPTION,
 NATURE_OF_ACTION_CODE,
 LATEST_EMPLOYEE_FAMILY_NAME,
 LATEST_EMPLOYEE_GIVEN_NAME,
 LATEST_EMPLOYEE_NUMBER,
 ORGANIZATION_ACTIVE_CODEA
  FROM {reporting_catalog}.bronze.hrsa_employee_history
),
E as (
  SELECT
  ACTV_FLG,
  EMP_FULL_NM,
  EMP_ID_NO,
  EMP_NO,
  END_DA,
  START_DA,
  SUPERVISOR_FLG,
  TITLE_CD,
  TITLE_DESC_TX
 FROM {reporting_catalog}.bronze.hrsa_employee
),
C as (
  SELECT
  ACCESSION_NATURE_OF_ACTION_DES,
  APPOINTMENT_TYPE_DESCRIPTION,  
  BUSINESS_UNIT_CODE,
  EMPLOYEE_ACCESSION_NATURE_OF_A,
  EMPLOYEE_ACCESSION_PAY_PERIOD_,
  EMPLOYEE_GIVEN_NAME,
  EMPLOYEE_CURRENT_FISCAL_YEAR,
  EMPLOYEE_EMPLOYMENT_STATUS_COD,
  EMPLOYEE_GRADE,
  EMPLOYEE_HIRED_DATE,
  DETAILEE_SUPERVISOR_EMPLOYEE_N,
  EMPLOYEE_NUMBER,
  DETAILEE_SUPERVISOR_DIM_ORGANI,
  EMPLOYEE_ORGANIZATION_CODE2,
  EMPLOYEE_POSITION_IDENTIFIER,
  EMPLOYEE_POSITION_NUMBER,
  DETAILEE_SUPERVISOR_ORGANIZATI,
  EMPLOYEE_POSITION_STATUS_CODE,
  EMPLOYEE_TENURE_GROUP_CODE,
  EMPLOYEE_REDUCTION_IN_FORCE_CO,
  EMPLOYEE_RETIREMENT_SERVICE_CO,
  EMPLOYEE_SEPARATION_ACCESSION_,
  EMPLOYEE_SEPARATION_DATE,
  EMPLOYEE_SEPARATION_FINAL_T_CO,
  EMPLOYEE_SEPARATION_NATURE_OF_,
  EMPLOYEE_SEPARATION_PARENT_LEAVE_CODE,
  EMPLOYEE_SEPARATION_PARENT_RET,
  EMPLOYEE_SEPARATION_PAY_PERIOD,
  EMPLOYEE_SEPARATION_TYPE_CODE,
  EMPLOYMENT_STATUS_DESCRIPTION,
  ORGANIZATION_CODE2,
  ORGANIZATION_FIFTH_LEVEL_CODE,
  ORGANIZATION_FIFTH_LEVEL_NAME,
  ORGANIZATION_FIRST_LEVEL_CODE,
  ORGANIZATION_FIRST_LEVEL_NAME,
  ORGANIZATION_FOURTH_LEVEL_CODE,
  ORGANIZATION_FOURTH_LEVEL_NAME,
  ORGANIZATION_NAME,
  ORGANIZATION_SECOND_LEVEL_CODE,
  ORGANIZATION_SECOND_LEVEL_NAME,
  ORGANIZATION_SIXTH_LEVEL_CODE,
  ORGANIZATION_SIXTH_LEVEL_NAME,
  ORGANIZATION_THIRD_LEVEL_CODE,
  ORGANIZATION_THIRD_LEVEL_NAME,
  PAY_PLAN_SOURCE_CODE,
  EMPLOYEE_VETERANS_STATUS_CODE,  
  SALARY_RATE_DESCRIPTION,
  SUPERVISOR_POSITION_NUMBER,
  SUPERVISOR_POSITION_SUPERVISOR,
  TENURE_GROUP_DESCRIPTION, 
  POSITION_NUMBER,
  SEPARATION_ACCESSION_TYPE_DESC,
  SEPARATION_FINAL_DESCRIPTION,
  SEPARATION_PRINT_DESCRIPTION,
  SEPARATION_TYPE_DESCRIPTION,
  TMOrg
FROM {reporting_catalog}.bronze.hrsa_current_employee
)

SELECT 
H.EMPLOYEE_NUMBER_VW_SL_HRSA_EM,
H.EMP_HIST_EMPLOYEE_NUMBER,
H.EMP_HIST_FROM_AGENCY_CODE,
H.EMP_HIST_FROM_DEPARTMENT_CODE,
H.EMP_HIST_FROM_ORGANIZATION_COD,
H.EMP_HIST_NATURE_OF_ACTION_DATE,
H.EMP_HIST_ORGANIZATION_CODE,
H.EMP_HIST_TO_AGENCY_CODE,
H.EMP_HIST_TO_DEPARTMENT_CODE,
H.EMP_HIST_TO_NATURE_OF_ACTION_C,
H.EMP_HIST_TO_NATURE_OF_ACTION_1,
H.EMP_HIST_TO_NATURE_OF_ACTION_D,
H.EMP_HIST_TO_ORGANIZATION_CODE,
H.NATURE_OF_ACTION_DESCRIPTION,
H.NATURE_OF_ACTION_CODE,
H.LATEST_EMPLOYEE_FAMILY_NAME,
H.LATEST_EMPLOYEE_GIVEN_NAME,
H.LATEST_EMPLOYEE_NUMBER,
H.ORGANIZATION_ACTIVE_CODEA,
E.ACTV_FLG,
E.EMP_FULL_NM,
E.EMP_ID_NO,
E.END_DA,
E.START_DA,
E.SUPERVISOR_FLG,
E.TITLE_CD,
E.TITLE_DESC_TX,
C.ACCESSION_NATURE_OF_ACTION_DES,
C.APPOINTMENT_TYPE_DESCRIPTION,  
C.BUSINESS_UNIT_CODE,
C.EMPLOYEE_ACCESSION_NATURE_OF_A,
C.EMPLOYEE_ACCESSION_PAY_PERIOD_,
C.EMPLOYEE_GIVEN_NAME,
C.EMPLOYEE_CURRENT_FISCAL_YEAR,
C.EMPLOYEE_EMPLOYMENT_STATUS_COD,
C.EMPLOYEE_GRADE,
C.EMPLOYEE_HIRED_DATE,
C.DETAILEE_SUPERVISOR_EMPLOYEE_N,
C.DETAILEE_SUPERVISOR_DIM_ORGANI,
C.EMPLOYEE_ORGANIZATION_CODE2,
C.EMPLOYEE_POSITION_IDENTIFIER,
C.EMPLOYEE_POSITION_NUMBER,
C.DETAILEE_SUPERVISOR_ORGANIZATI,
C.EMPLOYEE_POSITION_STATUS_CODE,
C.EMPLOYEE_TENURE_GROUP_CODE,
C.EMPLOYEE_REDUCTION_IN_FORCE_CO,
C.EMPLOYEE_RETIREMENT_SERVICE_CO,
C.EMPLOYEE_SEPARATION_ACCESSION_,
C.EMPLOYEE_SEPARATION_DATE,
C.EMPLOYEE_SEPARATION_FINAL_T_CO,
C.EMPLOYEE_SEPARATION_NATURE_OF_,
C.EMPLOYEE_SEPARATION_PARENT_LEAVE_CODE,
C.EMPLOYEE_SEPARATION_PARENT_RET,
C.EMPLOYEE_SEPARATION_PAY_PERIOD,
C.EMPLOYEE_SEPARATION_TYPE_CODE,
C.EMPLOYMENT_STATUS_DESCRIPTION,
C.ORGANIZATION_CODE2,
C.ORGANIZATION_FIFTH_LEVEL_CODE,
C.ORGANIZATION_FIFTH_LEVEL_NAME,
C.ORGANIZATION_FIRST_LEVEL_CODE,
C.ORGANIZATION_FIRST_LEVEL_NAME,
C.ORGANIZATION_FOURTH_LEVEL_CODE,
C.ORGANIZATION_FOURTH_LEVEL_NAME,
C.ORGANIZATION_NAME,
C.ORGANIZATION_SECOND_LEVEL_CODE,
C.ORGANIZATION_SECOND_LEVEL_NAME,
C.ORGANIZATION_SIXTH_LEVEL_CODE,
C.ORGANIZATION_SIXTH_LEVEL_NAME,
C.ORGANIZATION_THIRD_LEVEL_CODE,
C.ORGANIZATION_THIRD_LEVEL_NAME,
C.PAY_PLAN_SOURCE_CODE,
C.EMPLOYEE_VETERANS_STATUS_CODE,  
C.SALARY_RATE_DESCRIPTION,
C.SUPERVISOR_POSITION_NUMBER,
C.SUPERVISOR_POSITION_SUPERVISOR,
C.TENURE_GROUP_DESCRIPTION, 
C.POSITION_NUMBER,
C.SEPARATION_ACCESSION_TYPE_DESC,
C.SEPARATION_FINAL_DESCRIPTION,
C.SEPARATION_PRINT_DESCRIPTION,
C.SEPARATION_TYPE_DESCRIPTION,
C.TMOrg
FROM C
Left join E
ON C.EMPLOYEE_NUMBER = E.EMP_NO
Left JOIN H
ON C.EMPLOYEE_NUMBER = H.EMPLOYEE_NUMBER_VW_SL_HRSA_EM""")


# COMMAND ----------

df = join_query
df.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable(f"{reporting_catalog}.silver.edw_staffing_dashboard_info")
display(df)