schema:
    trgt_catalog: 'trm_efoiap'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'EFOIAP' 
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/EFOIAP'
    src_database: 'efoiap'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/efoiap'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/efoiap/transformed'
    finished_cdc_folder: 'eds/DMS/cdc/trm/efoiap/finished'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'       
    