schema:
    trgt_catalog: 'trm_eogadmin'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'EOGADMIN'
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/EOGADMIN'
    src_database: 'EOGADMIN'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/eogadmin'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/eogadmin/transformed'
    finished_cdc_folder: 'eds/DMS/cdc/trm/eogadmin/finished'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'    