schema:
    trgt_catalog: 'trm_jbteasps'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'TURM' 
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TURM'
    src_database: 'jbteasps'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/jbteasps'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/jbteasps/transformed'
    finished_cdc_folder: 'eds/DMS/cdc/trm/jbteasps/finished'
secrets:
    trm_scope: 'oracle_jbteasps_server'  
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'        