schema:
    trgt_catalog: 'trm_tmproceeding'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'TMPROCEEDING' 
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TMPROCEEDING'
    src_database: 'proceeding'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/tmproceeding'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/tmproceeding/transformed'
    finished_cdc_folder: 'eds/DMS/cdc/trm/tmproceeding/finished'
secrets:
    trm_scope: 'oracle_trm_server' 
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'
