schema:
    trgt_catalog: 'trm_tmintltm'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'tmintltm' 
    foreign_oracle_catalog: "foreign_trm_oracle"
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TMINTLTM'
    src_database: 'tmintltm'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/tmintltm'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/tmintltm/transformed_cdc'
    finished_cdc_folder: 'eds/DMS/cdc/trm/tmintltm/finished_cdc'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'   