schema:
    trgt_catalog: 'trm_tmngfpepp'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'TMNGFPEPP'
    dataload_dt: '2017-01-01 00:00:00'
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TMNGFPEPP'
    src_database: 'TMNGFPEPP'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/tmngfpepp'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/tmngfpepp/transformed_cdc'
    finished_cdc_folder: 'eds/DMS/cdc/trm/tmngfpepp/finished_cdc'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'
