schema:
    trgt_catalog: 'trm_tmngpdb'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'tmngpdb'
    bdx_api: 'http://bdr-bdx-wildfly-1.cld.uspto.gov:8080/bdr-bdx-dpl/startBdxDailyJob/Daily_tmappl_Xml?jobDate='
    s3_path: "s3://odp-prod-web/bulk-data/files/TRTDXFAP"  
    historical_file_batch_size: "155000"
    working_temp_directory: "dbfs:/mnt/eds/TRTDXFAP"
    s3_action_key_business_event_table_path: "s3://databricks-prod-tmdc/eds/trademark/bdss/Table_BDX_Action_Key_TM_Business_Event.xlsx"
    foreign_oracle_catalog: "foreign_trm_oracle"
    reporting_catalog: 'trm_reporting'
cdc:
    src_database: 'tmngpdb'
    cdc_bucket: 'databricks-prod-tmdc'
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TMNGPDB'
    cdc_folder: 'cdc'
secrets:
    trm_scope: 'oracle_trm_server'
    ptas_scope: 'orc_ptas_secret'
    part1_trm_scope: 'oracle_trm_server_dr'      
data_quality:
    receiver_email: ''
    brz_allowed_variance: '10.0'  
    tmapplser_quality_email_list: 'israel.alafe@uspto.gov,srinadh.guduru@uspto.gov,prasad.yellanki@uspto.gov'
DMS:
    groups: 12
    replication_instance: 'bdr-prod-databricks-dms'
    source_endpoint: 'trmprd-tmng-db-3'
    target_endpoint: 'dms-tmngpdb'
    initial_load_task_name: 'trm-tmngpdb-initial-load'
    full_load_task_name: 'trm-tmngpdb-full-load'
