schema:
    trgt_catalog: 'trm_tmworker'
    data_quality_catalog: 'data_quality' 
    src_db_name: 'TMWORKER'
    foreign_oracle_catalog: "foreign_trm_oracle"
cdc:
    src_csv_files: 's3a://databricks-prod-tmdc/eds/DMS/TMWORKER'
    src_database: 'TMWORKER'
    cdc_bucket: 'databricks-prod-tmdc'
    cdc_folder: 'eds/DMS/cdc/trm/tmworker'
    transformed_cdc_folder: 'eds/DMS/cdc/trm/tmworker/transformed'
    finished_cdc_folder: 'eds/DMS/cdc/trm/tmworker/finished'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ODBDDataLakeTeam@uspto.gov'
    brz_allowed_variance: '2.0'    