schema:
    trgt_catalog: 'trm_eogadmin_dev'
    data_quality_catalog: 'data_quality_dev' 
    src_db_name: 'EOGADMIN'
cdc:
    src_csv_files: 's3a://databricks-lab-tmdc/eds/DMS/EOGADMIN'
    src_database: 'EOGADMIN'
    cdc_bucket: 'databricks-lab-tmdc'
    cdc_folder: '/eds/DMS/cdc/trm/trm_eogadmin'
    transformed_cdc_folder: '/eds/DMS/cdc/trm/trm_eogadmin/transformed'
    finished_cdc_folder: '/eds/DMS/cdc/trm/trm_eogadmin/finished'
secrets:
    trm_scope: 'oracle_trm_server'      
data_quality:
    receiver_email: 'ravi.koppula1@uspto.gov'
    brz_allowed_variance: '10.0'   