schema:
    trgt_catalog: 'trm_jbteasps_dev'
    data_quality_catalog: 'data_quality_dev' 
    src_db_name: 'TURM' 
cdc:
    src_csv_files: 's3a://databricks-lab-tmdc/eds/DMS/TURM'
    src_database: 'jbteasqs'
    cdc_bucket: 'databricks-lab-tmdc'
    cdc_folder: '/eds/DMS/cdc/trm/trm_jbteasps'
    transformed_cdc_folder: '/eds/DMS/cdc/trm/trm_jbteasps/transformed'
    finished_cdc_folder: '/eds/DMS/cdc/trm/trm_jbteasps/finished'
secrets:
    trm_scope: 'oracle_jbteasps_server'
data_quality:
    receiver_email: 'ravi.koppula1@uspto.gov'
    brz_allowed_variance: '10.0'          
    