schema:
    trgt_catalog: 'trm_tmproceeding_dev'
    data_quality_catalog: 'data_quality_dev' 
    src_db_name: 'TMPROCEEDING' 
cdc:
    src_csv_files: 's3a://bdr-databricks-app-dev/eds/DMS/TMPROCEEDING'
    src_database: 'proceeding'
    cdc_bucket: 'databricks-lab-tmdc'
    cdc_folder: '/eds/DMS/cdc/trm/trm_tmproceeding'
    transformed_cdc_folder: '/eds/DMS/cdc/trm/trm_tmproceeding/transformed'
    finished_cdc_folder: '/eds/DMS/cdc/trm/trm_tmproceeding/finished'
secrets:
    trm_scope: 'oracle_trm_server'    
data_quality:
    receiver_email: 'ravi.koppula1@uspto.gov'
    brz_allowed_variance: '2.0'    