schema:
    trgt_catalog: 'trm_tmreviews_dev'
    data_quality_catalog: 'data_quality_dev' 
    src_db_name: 'TMREVIEWS' 
cdc:
    src_csv_files: 's3a://databricks-lab-tmdc/eds/DMS/TMREVIEWS'
    src_database: 'tmreviews'
    cdc_bucket: 'databricks-lab-tmdc'
    cdc_folder: '/eds/DMS/cdc/trm/trm_tmreviews'
    transformed_cdc_folder: '/eds/DMS/cdc/trm/trm_tmreviews/transformed'
    finished_cdc_folder: '/eds/DMS/cdc/trm/trm_tmreviews/finished'
secrets:
    trm_scope: 'oracle_trm_server'      
data_quality:
    receiver_email: 'ravi.koppula1@uspto.gov'
    brz_allowed_variance: '10.0'       
DMS:
    replication_instance: 'dbx-dev-orc-mig-s3'
    source_endpoint: 'pvt-tmng-db'
    target_endpoint: 'dms-tmreviews'
    delta_load_task_name: 'trm-tmreviews-delta-load'
    full_load_task_name: 'trm-tmreviews-full-load' 
    