schema:
  trgt_catalog: 'trm_tmrefdata_dev'
  data_quality_catalog: 'data_quality_dev' 
  src_db_name: 'TMREFDATA'
cdc:
  src_csv_files: 's3a://databricks-lab-tmdc/eds/DMS/TMREFDATA'
  src_database: 'TMREFDATA'
  cdc_bucket: 'databricks-lab-tmdc'
  cdc_folder: '/eds/DMS/cdc/trm/trm_tmrefdata'
  transformed_cdc_folder: '/eds/DMS/cdc/trm/tmrefdata/transformed'
  finished_cdc_folder: '/eds/DMS/cdc/trm/tmrefdata/finished'
secrets:
  trm_scope: 'oracle_trm_server'    
data_quality:
  receiver_email: 'robert.morris@uspto.gov'
  brz_allowed_variance: '2.0'    