# Databricks notebook source
# MAGIC %md
# MAGIC #####Schema = ["TABLE_GROUP_NAME","TABLE_NAME","FULL_LOAD","DQ_FLTR","LARGE_TABLE_IND","Cluster Columns"]

# COMMAND ----------

tmngpdb_metadata_group1 = [
    ('group1','TRADEMARK','Y','','L','TRADEMARK_GID'),
    ('group1','TM_LOCATIONS','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group1','TM_LITERAL','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),#reset back
    ('group1','TM_EMPLOYEE_ASSIGNMENT','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group1','TM_RELATIONSHIP','N','LAST_MOD_TS','','fk_parent_trademark_gid'),
    ('group1','TM_MILESTONE','Y','LAST_MOD_TS','','FK_TM_MILESTONE_CD,fk_trademark_gid'),#reset back
    ('group1','TM_ITU','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group1','TM_OFFICE_ACTIONS','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),#reset back
    ('group1','TM_DIVISIONAL_CHILD','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    #('group1','STND_TM_MILESTONE','N','LAST_MOD_TS','',''),
    ('group1','TM_PARTY_ROLE_OWNER','Y','LAST_MOD_TS','','fk_party_role_sequence_no,fk_trademark_gid'),#reset back
    ('group1','TM_CLASS_REFERENCE','Y','LAST_MOD_TS','','fk_class_id,fk_trademark_gid'),
    ('group1','USE_IN_ANOTHER_FORM','N','LAST_MOD_TS','','FK_CLASS_ID,fk_trademark_gid'),
    ('group1','ATTORNEY_HOLD','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    #('group1','INTERNATIONAL_REG_TM','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group1','BUSINESS_EVENT','Y','LAST_MOD_TS','','fk_business_event_reason_id,CFK_OBJECT_GID'),
    ('group1','STND_BUSINESS_EVENT_REASON','N','LAST_MOD_TS','','business_event_reason_id'),
    ('group1','STND_CLASS','N','LAST_MOD_TS','','CLASS_ID'),
    #('group1','STND_FEE_PROCESS_TYPE','N','LAST_MOD_TS','',''), 
    #('group1','STND_MARK_DRAWING_TYPE','N','LAST_MOD_TS','',''), 
]

# COMMAND ----------

tmngpdb_metadata_group11 = [
    ('group11','TM_FILING_BASIS_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group11','WORK_ITEM_OBJECT','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group11','TM_PARTY_ROLE','N','LAST_MOD_TS','','FK_TM_PARTY_ROLE_CD,TM_PARTY_ROLE_ID'),
    ('group11','TM_MAILING_ADDR','N','LAST_MOD_TS','','FK_TM_PARTY_ROLE_ID,FK_MAILING_ADDRESS_GID'),
    ('group11','TM_ELECTRONIC_ADDR','Y','LAST_MOD_TS','','FK_ELECTRONIC_ADDRESS_GID'),#reset back
    ('group11','TM_CLASS','N','LAST_MOD_TS','L',''),
    ('group11','INTERESTED_PARTY','Y','LAST_MOD_TS','L','interested_party_gid'),
    ('group11','MAILING_ADDRESS','Y','LAST_MOD_TS','','MAILING_ADDRESS_GID'),
    ('group11','ELECTRONIC_ADDRESS','N','LAST_MOD_TS','','ELECTRONIC_ADDRESS_GID'),
    ('group11','TM_FILING_BASIS','N','LAST_MOD_TS','','fk_filing_basis_cd,fk_trademark_gid'),
]

# COMMAND ----------

tmngpdb_metadata_group2 = [
    ('group2','ABANDONMENT_H','N','LAST_MOD_TS','','CFK_TRANSACTION_INSTANCE_GID'),
    ('group2','ABANDONMENT','N','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group2','ANNOTATION_COMMENT','Y','LAST_MOD_TS','','ANNOTATION_COMMENT_ID'),
    #('group2','BASE_APPLICATION','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    #('group2','BASE_APPLICATION_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group2','CONCURRENT_USE','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group2','DOCKET_ITEM','Y','LAST_MOD_TS','','DOCKET_ITEM_ID'),
    ('group2','DOCKET_ITEM_EVENT','N','LAST_MOD_TS','','FK_DOCKET_ITEM_ID'),
    ('group2','DOCKET_ITEM_H','Y','LAST_MOD_TS','','CFK_TRANSACTION_INSTANCE_GID, DOCKET_ITEM_ID'),
    ('group2','DRAFT_DOC_VER_COMPNT_FPV','N','LAST_MOD_TS','','FK_DRAFT_DOCUMENT_ID,CFK_FORM_PARAGRAPH_VERSION_GID'),
    ('group2','DRAFT_DOCUMENT','Y','LAST_MOD_TS','','DRAFT_DOCUMENT_ID'),#reset back
    ('group2','DRAFT_DOCUMENT_VERSION','Y','LAST_MOD_TS','','DRAFT_DOCUMENT_MOD_NO, FK_DRAFT_DOCUMENT_ID'),
    ('group2','DRAFT_DOCUMENT_VERSION_COMPNT','Y','LAST_MOD_TS','','FK_DOCUMENT_COMPONENT_ID'),#reset back
    ('group2','ELECTRONIC_ADDRESS_H','Y','LAST_MOD_TS','','ELECTRONIC_ADDRESS_GID,ACTION_CT'),
    ('group2','EMPLOYEE_AWARD_WITHDRAW','N','LAST_MOD_TS','','FK_AWARD_EMPE_CR_TRAN_ID, FK_WITHDRAW_EMPE_CR_TRAN_ID'),
    ('group2','EMPLOYEE_CREDIT_TRANSACTION','N','LAST_MOD_TS','','EMPLOYEE_CREDIT_TRAN_ID'),
    ('group2','EMPLOYEE_REVIEW_QUERY','N','LAST_MOD_TS','','EMPLOYEE_REVIEW_QUERY_ID'),
    ('group2','EMPLOYEE_REVIEW_QUERY_STAT','N','LAST_MOD_TS','','FK_EMPLOYEE_REVIEW_QUERY_ID'),
    ('group2','EMPLOYEE_TM_CLASS_CREDIT','N','LAST_MOD_TS','','FK_CLASS_ID, FK_TRADEMARK_GID'),
    ('group2','EVIDENCE_BIN_FOLDER','Y','LAST_MOD_TS','','EVIDENCE_BIN_FOLDER_ID'),
    ('group2','EVIDENCE_DOCUMENT','N','LAST_MOD_TS','','EVIDENCE_DOCUMENT_ID'),
    ('group2','FSM_INSTANCE','N','LAST_MOD_TS','','FSM_INSTANCE_GID'),
    ('group2','FSM_INSTANCE_H','Y','LAST_MOD_TS','','FSM_INSTANCE_GID'),#reset back
    ('group2','GDS_SRVC_STMT_ANNOTATION','N','LAST_MOD_TS','','FK_TRADEMARK_GID,FK_CLASS_ID'),
    ('group2','INTERESTED_PARTY_ASSUMED_NM','N','LAST_MOD_TS','','INTRSTD_PARTY_ASSUMED_NAME_ID'),
    ('group2','INTERESTED_PARTY_ASSUMED_NM_H','Y','LAST_MOD_TS','','INTRSTD_PARTY_ASSUMED_NAME_ID'),
    ('group2','INTERNAL_NOTE','Y','LAST_MOD_TS','','INTERNAL_NOTE_ID'),
    # ('group2','TRAM_UPD','N','','','UPD_RSN'),
    ('group2','TM_DRAWING','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group2','TM_DRAWING_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
]

# COMMAND ----------

tmngpdb_metadata_group3 = [ 
    #('group3','INTERNATIONAL_APPL_REG','N','LAST_MOD_TS','','FK_INTERNATIONAL_APPL_GID'),
    #('group3','INTERNATIONAL_APPL_REG_H','Y','LAST_MOD_TS','','FK_INTERNATIONAL_APPL_GID'),
    #('group3','INTERNATIONAL_APPLICATION','N','LAST_MOD_TS','','INTERNATIONAL_APPLICATION_GID'),
    #('group3','INTERNATIONAL_APPLICATION_H','Y','LAST_MOD_TS','','INTERNATIONAL_APPLICATION_GID'),
    #('group3','INTERNATIONAL_REG_TM_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    #('group3','INTERNATIONAL_REGISTRATION','N','LAST_MOD_TS','','INTERNATIONAL_REG_GID'),
    #('group3','INTERNATIONAL_REGISTRATION_H','Y','LAST_MOD_TS','','INTERNATIONAL_REG_GID'),
    #('group3','INTERNATIONAL_TM','N','LAST_MOD_TS','','INTERNATIONAL_REG_NO'),
    #('group3','INTERNATIONAL_TM_H','Y','LAST_MOD_TS','','INTERNATIONAL_REG_NO'),
    ('group3','IP_ELECTRONIC_ADDRESS','N','LAST_MOD_TS','','FK_ELECTRONIC_ADDRESS_GID'),
    ('group3','IP_MAILING_ADDRESS','N','LAST_MOD_TS','','FK_INTERESTED_PARTY_GID'),
    ('group3','IP_TELECOM_ADDRESS','N','LAST_MOD_TS','','FK_TELECOM_ADDRESS_GID'),
    # ('group3','MV_MYUSPTO_TRAM_SEARCH','Y','','','SERIAL_NUM'),
    ('group3','MV_MYUSPTO_TRM_SEARCH','Y','','','SERIAL_NUM'),
    ('group3','MV_MYUSPTO_TRM_AT','Y','','','TRADEMARK_GID'),
    ('group3','MV_MYUSPTO_TRM_MARK','Y','','','TRADEMARK_GID'),
    ('group3','MV_MYUSPTO_TRM_OWNER','Y','','','TRADEMARK_GID'),
    # ('group3','MV_MYUSPTO_TRAM_AT','Y','','','SER_NUM'),
    # ('group3','MV_MYUSPTO_TRAM_MARK','Y','','','SER_NUM'),
    # ('group3','MV_MYUSPTO_TRAM_OWNER','Y','','','SER_NUM'),
    #('group3','MYUSPTO_TRAM_CHANGE_NTFCN','Y','','','SERIAL_NUM'),
    #('group3','MYUSPTO_TRAM_EVENT_TODAY','Y','','','SERIAL_NUM'),
    #('group3','MYUSPTO_TRAM_PH','Y','','','SERIAL_NUM'),
    #('group3','MYUSPTO_TRAM_STATUS_TODAY','Y','','','SERIAL_NUM'),
    ('group3','MYUSPTO_TRM_CHANGE_NTFCN','Y','','','SERIAL_NUM'),
    ('group3','MYUSPTO_TRM_EVENT_TODAY','Y','','','SERIAL_NUM'),
    ('group3','MYUSPTO_TRM_PH','Y','','','SERIAL_NUM'),
    ('group3','MYUSPTO_TRM_STATUS_TODAY','Y','','','SERIAL_NUM'),  
    ('group3','OBJECT_DISPATCH','N','LAST_MOD_TS','','CFK_OBJECT_GID'),
    ('group3','OBJECT_DOCUMENT','Y','LAST_MOD_TS','','CFK_OBJECT_GID'),
    ('group3','OBJECT_DOCUMENT_H','Y','LAST_MOD_TS','','CFK_OBJECT_GID'),
    ('group3','OBJECT_FSM_INSTANCE','Y','LAST_MOD_TS','','CFK_OBJECT_GID'),
    ('group3','OFFICE_ACTIVITY','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group3','OFFICE_ACTIVITY_DRAFT_DOC_H','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group3','OFFICE_ACTIVITY_DRAFT_DOCUMENT','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),#reset back
    ('group3','OFFICE_ACTIVITY_H','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group3','OFFICE_ACTIVITY_REASON','N','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group3','OFFICE_ACTIVITY_REASON_H','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'),
    ('group3','OFFICE_ACTIVITY_REVIEW','Y','LAST_MOD_TS','','OFFICE_ACTIVITY_REVIEW_ID'),
    ('group3','TRANSACTION_INSTANCE','Y','LAST_MOD_TS','L','TRANSACTION_INSTANCE_GID'),
    ('group3','TM_DOCUMENT','Y','LAST_MOD_TS','','TM_DOCUMENT_ID'),
    ('group3','TM_DOCUMENT_REFERENCE','Y','LAST_MOD_TS','','FK_TM_DOCUMENT_ID'),
]

# COMMAND ----------

tmngpdb_metadata_group4 = [ 
    ('group4','OG_TM_REVIEW','N','LAST_MOD_TS','','OG_TM_REVIEW_GID'),
    ('group4','PRCDNG_EMPLOYEE_ASSIGNMENT','N','LAST_MOD_TS','','CFK_PROCEEDING_GID'),
    ('group4','PRCDNG_EMPLOYEE_ASSIGNMENT_H','Y','LAST_MOD_TS','','CFK_PROCEEDING_GID'),#reset back
    ('group4','PREDEFINED_PARAGRAPH','N','LAST_MOD_TS','','PREDEFINED_PARAGRAPH_ID'),
    ('group4','PREDEFINED_PARAGRAPH_VER','N','LAST_MOD_TS','','FK_DOCUMENT_COMPONENT_ID'),
    ('group4','QUERY_APPEAL','N','LAST_MOD_TS','','QUERY_APPEAL_GID'),
    ('group4','QUERY_APPEAL_STATUS','N','LAST_MOD_TS','','FK_EMPLOYEE_QUERY_APPEAL_ID'),
    ('group4','QUERY_GROUND','N','LAST_MOD_TS','','QUERY_GROUND_ID'),
    ('group4','RELATED_WORKER','N','LAST_MOD_TS','','RELATED_WORKER_ID'),
    ('group4','REVIEW_ANNOTATION','Y','LAST_MOD_TS','','REVIEW_ANNOTATION_ID'),
    ('group4','REVIEW_QUERY_APPEAL','N','LAST_MOD_TS','','REVIEW_QUERY_APPEAL_ID'),
    ('group4','REVIEW_QUERY_CLASS','N','LAST_MOD_TS','','FK_QUERY_GROUND_ID'),
    ('group4','REVIEW_QUERY_NOTE','N','LAST_MOD_TS','','FK_REVIEW_QUERY_GID'),
    ('group4','SECTION_2F_STATEMENT','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group4','STND_DESIGN_SEARCH_CODE_ITEM','N','LAST_MOD_TS','','FK_DESIGN_SEARCH_GROUP_CD'),
    ('group4','STND_DESIGN_SEARCH_GROUP','N','LAST_MOD_TS','','DESIGN_SEARCH_GROUP_CD'),
    ('group4','TM_ADDL_STMNT_PRIOR_REG','N','LAST_MOD_TS','','FK_STATEMENT_TYPE_CD, FK_TRADEMARK_GID'),
    ('group4','TM_ADDL_STMNT_PRIOR_REG_H','Y','LAST_MOD_TS','','FK_STATEMENT_TYPE_CD, FK_TRADEMARK_GID'),
    ('group4','TM_AMENDMENT','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group4','TM_CLASS_FILING_BASIS','N','LAST_MOD_TS','','FK_FILING_BASIS_CD, FK_TRADEMARK_GID'),
    ('group4','TM_EMPLOYEE_ASSIGNMENT_H','Y','LAST_MOD_TS','','FK_TM_EMPLOYEE_ROLE_CD, FK_TRADEMARK_GID'), 
    #('group4','TRAM_PQR','Y','','','PQR_RSN'),
    #('group4','TRAM_PRN','Y','','','PRN_RSN'),
    #('group4','TRAM_PQRE','Y','','','PQRE_RSN'),   
    #('group4','TRAM_PRNA','Y','','','PRNA_RSN'),
    ('group4','TEMP_TRM_PQ','Y','','',''),
    ('group4','TEMP_TRM_PQ_H','Y','','',''),
    ('group4','TEMP_TRM_PQC','Y','','',''),   
    ('group4','TEMP_TRM_PQC_H','Y','','',''),
    ('group4','SUBMISSION','Y','LAST_MOD_TS','','SUBMISSION_GID'), 
    ('group4','SUBMISSION_H','Y','LAST_MOD_TS','','SUBMISSION_GID'), 
    ('group4','SUBMISSION_ITEM','Y','LAST_MOD_TS','','SUBMISSION_ITEM_GID'), 
    ('group4','SUBMISSION_ITEM_H','Y','LAST_MOD_TS','','SUBMISSION_ITEM_GID'), 
    ('group4','SYNC_CASESTATUS','N','CS_TIMESTAMP','','CS_SERIAL_NUM'), 
    ('group4','SYNC_EXCEPTIONS','Y','INSERT_DT','','SYNC_EXCEPTIONS_ID'), 
    #('group4','SYNC_LOG','Y','CREATEDATE','',''), 
    ('group4','SYNC_TM_COM_EXCEPTION','Y','RESOLVED_TS','','TM_COM_EXCEPTION_ID'), 
    #('group4','SYNC_TRAM_TRM_OBJ_ID_MAPPING','Y','','',''), 
    #('group4','SYNC_TRM_TO_TRAM_CONTROL','Y','LAST_MOD_TS','','TRM_TRAM_SYNC_CONTROL_ID'), 
    ('group4','TELECOM_ADDRESS','Y','LAST_MOD_TS','','TELECOM_ADDRESS_GID'), 
    ('group4','TELECOM_ADDRESS_H','Y','LAST_MOD_TS','','TELECOM_ADDRESS_GID'), 
    ('group4','TM_ADDITIONAL_STATEMENT','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group4','WORK_ITEM_OBJECT_H','Y','LAST_MOD_TS','','FK_WORK_ITEM_GID'), 
    # ('group4','TRAM_VT','N','','','VT_RSN'),
]                                                      

# COMMAND ----------

# DBTITLE 1,Group5 Runs on Weekly schedule
tmngpdb_metadata_group5 = [ 
    ('group5','STND_TM_MILESTONE','N','LAST_MOD_TS','',''),
    ('group5','STND_FEE_PROCESS_TYPE','N','LAST_MOD_TS','',''), 
    ('group5','STND_MARK_DRAWING_TYPE','N','LAST_MOD_TS','',''), 
    ('group5','TM_GDS_SRVC_TERM_FILG_BASIS','N','LAST_MOD_TS','',''),
    ('group5','TM_GDS_SRVC_TERM_FILG_BASIS_H','N','LAST_MOD_TS','',''),
    ('group5','CUSTOM_ALERT','N','LAST_MOD_TS','','CUSTOM_ALERT_ID'),
    ('group5','DOCKET_ITEM_EVENT_H','N','LAST_MOD_TS','','CFK_TRANSACTION_INSTANCE_GID,FK_DOCKET_ITEM_ID'),
    ('group5','DOCUMENT_COMPONENT_RELTNSP','N','LAST_MOD_TS','','FK_PARENT_DOCUMENT_COMPNT_ID'),
    ('group5','EVIDENCE_BIN_FOLDER_H','Y','LAST_MOD_TS','','EVIDENCE_BIN_FOLDER_ID'),
    ('group5','FORM_PARAGRAPH_RULE','N','LAST_MOD_TS','','FORM_PARAGRAPH_RULE_ID'),
    #('group5','IB_TRANSACTION','N','','','FK_WORK_ITEM_GID'),
    ('group5','DOCUMENT_TEMPLATE_VERSION','N','LAST_MOD_TS','','fk_document_template_cd'),
    ('group5','EMPLOYEE_QUERY_APPEAL','N','LAST_MOD_TS','','EMPLOYEE_QUERY_APPEAL_ID'),
    ('group5','EVIDENCE_DOCUMENT_H','Y','LAST_MOD_TS','','EVIDENCE_DOCUMENT_ID'),
    ('group5','DOC_TMPLT_VER_FORM_PARA','Y','LAST_MOD_TS','','DOC_TMPLT_VER_FORM_PARA_ID'),
    ('group5','INTRSTD_PARTY_RELATIONSHIP','N','LAST_MOD_TS','','FK_INTERESTED_PARTY_GID'),
    ('group5','INTRSTD_PARTY_RELATIONSHIP_H','N','LAST_MOD_TS','','FK_INTERESTED_PARTY_GID'),
    ('group5','IR_MAILING_ADDRESS','N','LAST_MOD_TS','','FK_MAILING_ADDRESS_GID'),
    ('group5','IR_MAILING_ADDRESS_GROUP','N','LAST_MOD_TS','','FK_INTERNATIONAL_REG_GID'),
    ('group5','MAILING_ADDRESS_LINE','N','LAST_MOD_TS','','FK_MAILING_ADDRESS_GID'),
    ('group5','MAILING_ADDRESS_LINE_H','N','LAST_MOD_TS','','FK_MAILING_ADDRESS_GID'),
    ('group5','QUERY_APPEAL_NOTE','N','LAST_MOD_TS','','FK_EMPLOYEE_QUERY_APPEAL_ID'),
    ('group5','REVIEW_ISSUE','N','LAST_MOD_TS','','FK_OFFICE_ACTIVITY_REVIEW_ID'),
    ('group5','REVIEW_QUERY','N','LAST_MOD_TS','','REVIEW_QUERY_GID'),
    #('group5','SECTION_2F_PRIOR_REG','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    #('group5','SECTION_2F_PRIOR_REG_H','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group5','STND_ANNOTATION_STATUS','N','LAST_MOD_TS','','ANNOTATION_STATUS_CD'),
    ('group5','STND_APPEAL_RESULT','N','LAST_MOD_TS','','APPEAL_RESULT_CD'),
    ('group5','STND_APPEAL_STATUS','N','LAST_MOD_TS','','APPEAL_STATUS_CD'),
    ('group5','STND_ASSUMED_NAME_TYPE','N','LAST_MOD_TS','','ASSUMED_NAME_TYPE_CD'),
    ('group5','STND_AVERMENT','N','LAST_MOD_TS','','AVERMENT_ID'),
    ('group5','STND_BUSINESS_EVENT_RSN_CT','N','LAST_MOD_TS','','BUSINESS_EVENT_RSN_CT_CD'),
    ('group5','STND_CATEGORY_DOC_TYPE','N','LAST_MOD_TS','','FK_DOCUMENT_TYPE_ID'),
    ('group5','STND_CLASS_SCHEDULE','N','LAST_MOD_TS','','CLASS_SCHEDULE_CD'),
    ('group5','STND_CLASS_STATEMENT_TYPE','N','LAST_MOD_TS','','CLASS_STATEMENT_TYPE_CD'),
    ('group5','STND_COORDINATED_CLASS','N','LAST_MOD_TS','','FK_CLASS_ID, FK_COORDINATED_CLASS_ID'),
    ('group5','STND_CREDIT_TRAN_RSN_TYPE','N','LAST_MOD_TS','','CREDIT_TRAN_RSN_TYPE_CD'),
    ('group5','STND_DESIGN_SEARCH_GROUP_TYPE','N','LAST_MOD_TS','','DESIGN_SEARCH_GROUP_TYPE_CD'),
    ('group5','STND_DOC_TYPE_CT','N','LAST_MOD_TS','','DOC_TYPE_CT_ID'),
    ('group5','STND_DOCKET','N','LAST_MOD_TS','','DOCKET_ID'),
    ('group5','STND_DOCKET_FSM_TYPE_STATE','N','LAST_MOD_TS','','CFK_FSM_TYPE_STATE_ID, FK_DOCKET_ID'),
    ('group5','STND_DOCKET_ITEM_EVENT_TYPE','N','LAST_MOD_TS','','DOCKET_ITEM_EVENT_TYPE_CD'),
    ('group5','STND_DOCUMENT_COMPONENT_TYPE','N','LAST_MOD_TS','','DOCUMENT_COMPONENT_TYPE_CD'),
    ('group5','STND_DOCUMENT_TEMPLATE','N','LAST_MOD_TS','','DOCUMENT_TEMPLATE_CD'),
    ('group5','STND_DOCUMENT_TYPE','N','LAST_MOD_TS','','DOCUMENT_TYPE_ID'),
    ('group5','STND_ELECTRONIC_ADDR_TYPE','N','LAST_MOD_TS','','ELECTRONIC_ADDR_TYPE_CD'),
    ('group5','STND_EVIDENCE_BIN','N','LAST_MOD_TS','','EVIDENCE_BIN_CD'),
    ('group5','TM_CLASS_GDS_SRVC_TERM','N','LAST_MOD_TS','','FK_TRADEMARK_GID, SEQUENCE_NO'),
    ('group5','TM_CLASS_GDS_SRVC_TERM_H','N','LAST_MOD_TS','','FK_TRADEMARK_GID, SEQUENCE_NO'),
    ('group5','STND_EVIDENCE_SOURCE_CATEGORY','N','LAST_MOD_TS','','EVIDENCE_SOURCE_CATEGORY_CD'), 
    ('group5','STND_FILING_BASIS','N','LAST_MOD_TS','','FILING_BASIS_CD'), 
    ('group5','STND_FSM_CATEGORY','N','LAST_MOD_TS','','FSM_CATEGORY_CD'), 
    ('group5','STND_FSM_STATE_LEGACY_STATE','N','LAST_MOD_TS','','CFK_FSM_TYPE_STATE_ID'), 
    ('group5','STND_FSM_TYPE','N','LAST_MOD_TS','','FSM_TYPE_ID'),
    ('group5','STND_GDS_SRVC_ANNOTN_STAT','N','LAST_MOD_TS','','GDS_SRVC_ANNOTN_STATUS_CD'), 
    ('group5','STND_GDS_SRVC_MATCH_STAT','N','LAST_MOD_TS','','GDS_SRVC_MATCH_STAT_CD'), 
    ('group5','STND_GDS_SRVC_STATUS','N','LAST_MOD_TS','','GDS_SRVC_STATUS_CD'), 
    ('group5','STND_GROUND','N','LAST_MOD_TS','','FK_GROUND_TYPE_CD'), 
    ('group5','STND_GROUND_TYPE','N','LAST_MOD_TS','','GROUND_TYPE_CD'), 
    ('group5','STND_INTRSTD_PARTY_RLTNSP_TYPE','N','LAST_MOD_TS','','INTRSTD_PARTY_RELTNSP_TYPE_CD'),
    ('group5','STND_LEGACY_TRANSACTION','N','LAST_MOD_TS','','LEGACY_TRANSACTION_CD'), 
    ('group5','STND_LEGAL_ENTITY_TYPE','N','LAST_MOD_TS','','LEGAL_ENTITY_TYPE_CD'), 
    ('group5','STND_MAD_BIRTH_REC_CT_TYPE','N','LAST_MOD_TS','','MAD_BIRTH_REC_CT_TYPE_CD'), 
    ('group5','STND_MAD_TRANSACTION_TYPE','N','LAST_MOD_TS','','MAD_TRANSACTION_TYPE_CD'), 
    ('group5','STND_MARK_TYPE','N','LAST_MOD_TS','','MARK_TYPE_CD'), 
    ('group5','STND_MYUSPTO_EVENT','N','','','EVENT_CD'), 
    ('group5','STND_NOTE_TYPE','N','LAST_MOD_TS','','NOTE_TYPE_CD'), 
    ('group5','STND_OBJECT_DISPATCH_TYPE','N','LAST_MOD_TS','','OBJECT_DISPATCH_TYPE_CD'), 
    ('group5','STND_OBJECT_TYPE','N','LAST_MOD_TS','','OBJECT_TYPE_CD'), 
]

# COMMAND ----------

# DBTITLE 1,Group6 Runs on Weekly schedule
tmngpdb_metadata_group6 = [
    ('group6','STND_OFFICE_ACTION_CATEGORY','N','LAST_MOD_TS','','OFFICE_ACTION_CATEGORY_CD'), 
    ('group6','STND_OFFICE_ACTION_RULE','N','LAST_MOD_TS','','FK_OFFICE_ACTION_CATEGORY_CD, FK_WORK_ITEM_TYPE_CD'), 
    ('group6','STND_OFFICE_ACTIVITY_REASON','N','LAST_MOD_TS','','OFFICE_ACTIVITY_REASON_CD'), 
    ('group6','STND_OFFICE_ACTVTY_RSN_CT','N','LAST_MOD_TS','','OFFICE_ACTVTY_RSN_CT_CD'), 
    ('group6','STND_OWNER_TYPE','N','LAST_MOD_TS','','OWNER_TYPE_ID'), 
    ('group6','STND_PAY_PERIOD','N','LAST_MOD_TS','','FISCAL_YEAR_NO,PERIOD_NO'), 
    ('group6','STND_PRCDNG_EMPE_ASGMT_ROLE','N','LAST_MOD_TS','','PRCDNG_EMPLOYEE_ROLE_CD'), 
    ('group6','STND_PUBLICATION_CATEGORY','N','LAST_MOD_TS','','PUBLICATION_CATEGORY_CD'), 
    ('group6','STND_PUBLICATION_SUBCATEGORY','N','LAST_MOD_TS','','FK_PUBLICATION_CATEGORY_CD, PUBLICATION_SUBCATEGORY_CD'), 
    ('group6','STND_QUERY_REVIEW_STATUS','N','LAST_MOD_TS','','QUERY_REVIEW_STATUS_CD'), 
    ('group6','STND_REG_STMNT_TYPE','N','LAST_MOD_TS','','REG_STMNT_TYPE_CD'), 
    ('group6','STND_RELATIONSHIP_TYPE','N','LAST_MOD_TS','','RELATIONSHIP_TYPE_CD'), 
    ('group6','STND_RESPONSE_ISSUE','N','LAST_MOD_TS','','RESPONSE_ISSUE_CD'), 
    ('group6','STND_REVIEW_ISSUE','N','LAST_MOD_TS','','REVIEW_ISSUE_CD'), 
    ('group6','STND_REVIEW_RATING','N','LAST_MOD_TS','','REVIEW_RATING_CD'), 
    ('group6','STND_STATEMENT_TYPE','N','LAST_MOD_TS','','STATEMENT_TYPE_CD'), 
    ('group6','STND_SUBMISSION_METHOD','N','LAST_MOD_TS','','SUBMISSION_METHOD_CD'), 
    ('group6','STND_TELECOM_FORMAT','N','LAST_MOD_TS','','TELECOM_FORMAT_CD'), 
    ('group6','STND_TELECOM_TYPE','N','LAST_MOD_TS','','TELECOM_TYPE_CD'), 
    ('group6','STND_TEMPLATE_PARA_TYPE','N','LAST_MOD_TS','','TEMPLATE_PARA_TYPE_CD'), 
    ('group6','STND_TM_AMENDMENT_REASON','N','LAST_MOD_TS','','TM_AMENDMENT_REASON_CD'), 
    ('group6','STND_TM_CLASS_STATUS','N','LAST_MOD_TS','','TM_CLASS_STATUS_CD'),
    ('group6','STND_TM_DIVISIONAL_STATUS','N','LAST_MOD_TS','','TM_DIVISIONAL_STATUS_CD'), 
    ('group6','STND_TM_EMPLOYEE_ASGMT_ROLE','N','LAST_MOD_TS','','TM_EMPLOYEE_ROLE_CD'), 
    ('group6','STND_TM_GROUP_TYPE','N','LAST_MOD_TS','','TM_GROUP_TYPE_CD'), 
    ('group6','STND_TM_INTRSTD_PARTY_ROLE','N','LAST_MOD_TS','','TM_INTRSTD_PARTY_ROLE_CD'), 
    ('group6','STND_TM_PARTY_ROLE','N','LAST_MOD_TS','','TM_PARTY_ROLE_CD'), 
    ('group6','STND_TM_REVIEW_STATUS','N','LAST_MOD_TS','','TM_REVIEW_STATUS_CD'), 
    ('group6','STND_US_INTL_CLS_MAPPING','N','LAST_MOD_TS','','FK_INTL_CLASS_ID, FK_US_CLASS_ID'), 
    ('group6','STND_WORK_ITEM_RELTNSP_TYPE','N','LAST_MOD_TS','','WORK_ITEM_RELATIONSHIP_CD'), 
    ('group6','STND_WORK_ITEM_REQUEST','N','LAST_MOD_TS','','WORK_ITEM_REQUEST_CD'), 
    ('group6','STND_WORK_ITEM_TYPE','Y','LAST_MOD_TS','','WORK_ITEM_TYPE_CD'), 
    ('group6','STND_WORK_ITEM_TYPE_DOC_TMPLT','N','LAST_MOD_TS','','FK_DOCUMENT_TEMPLATE_CD, FK_WORK_ITEM_TYPE_CD'), 
    ('group6','STND_WORK_ITEM_TYPE_RULE','N','LAST_MOD_TS','','WORK_ITEM_TYPE_RULE_ID'), 
    ('group6','STND_WORKER_RELTNSP_TYPE','N','LAST_MOD_TS','','WORKER_RELATIONSHIP_CD'), 
    ('group6','STND_WRITING_RVW_ADDL_ACTN','N','LAST_MOD_TS','','WRITING_RVW_ADDL_ACTN_CD'), 
    ('group6','SUBMISSION_AVERMENT','N','LAST_MOD_TS','','FK_SUBMISSION_GID, SEQUENCE_NO'), 
    ('group6','SUBMISSION_AVERMENT_H','N','LAST_MOD_TS','','FK_SUBMISSION_GID, SEQUENCE_NO'), 
    ('group6','SUBMISSION_ELCTRN_ADDR','N','LAST_MOD_TS','','FK_ELECTRONIC_ADDRESS_GID, FK_SUBMISSION_GID'), 
    ('group6','SUBMISSION_ELCTRN_ADDR_H','N','LAST_MOD_TS','','FK_ELECTRONIC_ADDRESS_GID, FK_SUBMISSION_GID'), 
    ('group6','SUBMISSION_SIGNATURE','N','LAST_MOD_TS','','FK_SUBMISSION_GID, SEQUENCE_NO'), 
    #('group6','SYNC_AUTHUSER','Y','LASTUPDATED','',''), 
    ('group6','SYNC_CASELOCK','Y','','',''), 
    #('group6','SYNC_CHECKPOINT','N','END_TS','','SCRIPT_NM, START_TS'), 
    #('group6','SYNC_EXCEPTION_TYPE','Y','','',''), 
    #('group6','SYNC_MIGRATION_RULES','Y','','',''), 
    #('group6','SYNC_MIGRATION_SCRIPT','N','','','SCRIPT_NUM'), 
    ('group6','SYNC_RUNTIME','Y','','',''), 
    ('group6','SYNC_STND_AM_STAT','N','','','AM_STAT'), 
    #('group6','SYNC_TRANLOG','Y','','',''), 
    ('group6','SYNC_TRANSLATE_ASSUMED_NAME','Y','','',''), 
    ('group6','SYNC_TRANSLATE_EMP_LO','Y','','',''), 
    ('group6','SYNC_TRANSLATE_EP','Y','','',''), 
    ('group6','SYNC_TRANSLATE_GEO','N','','','LEGACY_CD'), 
    ('group6','SYNC_TRANSLATE_LOCATION','Y','','',''), 
    ('group6','SYNC_TRANSLATE_OG_CATG','N','','','OG_CAT'), 
    ('group6','SYNC_TRANSLATE_PARTY_TYPE','N','','','LEGACY_PARTY_TYPE'), 
    ('group6','SYNC_TRANSLATE_PETITION_DOCKT','N','','','DOC_TYPE_CD'), 
    ('group6','SYNC_TRANSLATE_WORK_ITEM_CMS','Y','','',''),
    #('group6','TRAM_CT','N','','','CT_RSN'),
    #('group6','TRAM_DES','N','','','DES_RSN'), 
    #('group6','TRAM_DSC','N','','','DSC_RSN'), 
    #('group6','TRAM_ECR','Y','','',''), 
    #('group6','TRAM_GS','N','','','GS_RSN'),
    #('group6','TRAM_OI','N','','','OI_RSN'),
    #('group6','TRAM_OT','N','','','OT_RSN'),
    #('group6','TRAM_PD','N','','','PD_RSN'),
    #('group6','TRAM_PSC','N','','','PSC_RSN'), 
    #('group6','TRAM_QE','N','','','QE_RSN'), 
    #('group6','TRAM_RQ','N','','','RQ_RSN'), 
    #('group6','TRAM_RT','N','','','RT_RSN'), 
    #('group6','TRAM_SC','N','','','SC_RSN'), 
    #('group6','TRAM_STC','N','','','stc_iso_nm'), 
    #('group6','TRAM_TE','N','','','TE_RSN'), 
    #('group6','TRAM_TH','N','','','TH_RSN'), 
    #('group6','TRAM_TT1','N','','','TT_RSN'), 
    #('group6','TRAM_TY','N','','','TY_RSN'),
    #('group6','TRAM_WT','N','','','WT_RSN'), 
    #('group6','TRAM_TG','N','','','TG_RSN'),
    ('group6','WORKER','N','LAST_MOD_TS','','WORKER_GID'), 
    ('group6','WORKER_H','N','LAST_MOD_TS','','WORKER_GID'), 
    ('group6','DOCUMENT_COMPONENT','N','LAST_MOD_TS','L',''),
]
    

# COMMAND ----------

tmngpdb_metadata_group7 = [
    ('group7','TM_ADDITIONAL_STATEMENT_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','OG_PUBLICATION','N','LAST_MOD_TS','','OG_PUBLICATION_GID'), 
    ('group7','OG_PUBLICATION_H','N','LAST_MOD_TS','','OG_PUBLICATION_GID'), 
    ('group7','OG_PUBLICATION_TM','Y','LAST_MOD_TS','','FK_OG_PUBLICATION_GID'), 
    ('group7','OG_PUBLICATION_TM_H','Y','LAST_MOD_TS','','FK_OG_PUBLICATION_GID'), 
    ('group7','SECTION_2F_STATEMENT_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_DESIGN_ELEMENT','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),   
    ('group7','TM_REGISTRATION_STATEMENT_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_RELATIONSHIP_H','N','LAST_MOD_TS','','FK_PARENT_TRADEMARK_GID'), 
    ('group7','TRADEMARK_H','Y','LAST_MOD_TS','L','TRADEMARK_GID'),
    ('group7','MAILING_ADDRESS_H','Y','LAST_MOD_TS','','MAILING_ADDRESS_GID'), 
    ('group7','INTERESTED_PARTY_H','Y','LAST_MOD_TS','L','INTERESTED_PARTY_GID'),
    ('group7','CONCURRENT_USE_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','USE_IN_ANOTHER_FORM_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_PSEUDO_MARK_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_PUBLICATION','Y','LAST_MOD_TS','','TM_PUBLICATION_GID'), 
    ('group7','TM_PUBLICATION_H','Y','LAST_MOD_TS','','TM_PUBLICATION_GID'), 
    ('group7','TM_PUBLICATION_SUBCT','N','LAST_MOD_TS','','FK_TM_PUBLICATION_GID'), 
    ('group7','TM_PUBLICATION_SUBCT_H','Y','LAST_MOD_TS','','FK_TM_PUBLICATION_GID'), 
    ('group7','TM_CLASS_H','Y','LAST_MOD_TS','L','FK_TRADEMARK_GID'),
    ('group7','TM_FOREIGN_BASIS_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_PARTY_ROLE_H','Y','LAST_MOD_TS','','TM_PARTY_ROLE_ID'), 
    ('group7','TM_PRIOR_REGISTRATION_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group7','TM_MILESTONE_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
]

# COMMAND ----------

tmngpdb_metadata_group8 = [
    ('group8','TM_DIVISIONAL','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    ('group8','TM_DIVISIONAL_CHILD_H','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group8','TM_DIVISIONAL_H','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group8','TM_REGISTRATION_STATEMENT','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),     
    ('group8','TM_RENEWAL','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group8','TM_RENEWAL_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group8','TM_TELECOM_ADDR','N','LAST_MOD_TS','','FK_TELECOM_ADDRESS_GID'), 
    ('group8','TM_TELECOM_ADDR_H','Y','LAST_MOD_TS','','FK_TELECOM_ADDRESS_GID'), 
    #('group8','TRAM_AM','N','','','am_exmr_num'), 
    #('group8','TRAM_AMQ','N','','','AMQ_RSN'), 
    #('group8','TRAM_AMQE','N','','','AMQE_RSN'), 
    #('group8','TRAM_ATH','N','','','ATH_RSN'), 
    #('group8','TRAM_CAC','N','','','CAC_RSN'), 
    #('group8','TRAM_CAD','N','','','CAD_RSN'), 
    #('group8','TRAM_CB','N','','','CB_RSN'), 
    #('group8','TRAM_CDH','N','','','CDH_RSN'), 
    #('group8','TRAM_COP','N','','','COP_RSN'), 
    #('group8','TRAM_CRQ','N','','','CRQ_RSN'), 
    #('group8','TRAM_DV','N','','','DV_RSN'), 
    #('group8','TRAM_DVC','N','','','DVC_RSN'), 
    #('group8','TRAM_EE','N','','','EE_RSN'), 
    #('group8','TRAM_EM','N','','','EM_RSN'), 
    #('group8','TRAM_EMA','N','','','EMA_RSN'), 
    #('group8','TRAM_EME','N','','','EME_RSN'), 
    #('group8','TRAM_EML','N','','','EML_RSN'), 
    #('group8','TRAM_EP','N','','','EP_RSN'), 
    #('group8','TRAM_FN','N','','','FN_RSN'), 
    #('group8','TRAM_FPR','N','','','FPR_RSN'), 
    #('group8','TRAM_FT','N','','','FT_RSN'), 
    #('group8','TRAM_IU','N','','','IU_RSN'), 
    #('group8','TRAM_IX','N','','','IX_RSN'), 
    #('group8','TRAM_JN','N','','','JN_RSN'), 
    #('group8','TRAM_MAD','N','','','mad_intl_reg_num'), 
    #('group8','TRAM_MAS','N','','','MAS_RSN'), 
    #('group8','TRAM_MD','N','','','MD_RSN'), 
    #('group8','TRAM_MHI','N','','','MHI_RSN'), 
    #('group8','TRAM_MIF','N','','','MIF_RSN'), 
    #('group8','TRAM_MN','N','','','MN_RSN'), 
    #('group8','TRAM_NI','N','','','NI_RSN'), 
    #('group8','TRAM_OG','N','','','OG_RSN'), 
    #('group8','TRAM_OGH','N','','','OGH_RSN'), 
    ('group8','tmcom_batch_ingest_control','Y','','',''), 
]

# COMMAND ----------

tmngpdb_metadata_group9 = [
    #('group9','TRAM_PAS','N','','','PAS_RSN'), 
    #('group9','TRAM_PCM','N','','','PCM_RSN'), 
    #('group9','TRAM_PI','N','','','pi_catg'), 
    #('group9','TRAM_PLH','N','','','PLH_RSN'), 
    #('group9','TRAM_PQ','N','','','PQ_RSN'), 
    #('group9','TRAM_PQC','N','','','PQC_RSN'), 
    #('group9','TRAM_PR','N','','','PR_RSN'), 
    #('group9','TRAM_PSL','N','','','PSL_RSN'), 
    #('group9','TRAM_PX','N','','','PX_RSN'), 
    #('group9','TRAM_PXC','N','','','PXC_RSN'), 
    #('group9','TRAM_PXQ','N','','','PXQ_RSN'), 
    #('group9','TRAM_PY','N','','','PY_RSN'), 
    #('group9','TRAM_RI','N','','','RI_RSN'), 
    #('group9','TRAM_SSR','N','','','SSR_RSN'), 
    #('group9','TRAM_TM','N','','','TM_RSN'), 
    #('group9','TRAM_TP','N','','','tp_cls_intl_ct'), 
    #('group9','TRAM_TQR','N','','','tqr_ser_num'), 
    #('group9','TRAM_TRM','N','','','TRM_RSN'), 
    #('group9','TRAM_TS','N','','','TS_RSN'), 
    #('group9','TRAM_TT','N','','','TT_RSN'), 
    #('group9','TRAM_VH','N','','','VH_RSN'),  
    #('group9','TRAM_WP','N','','','WP_RSN'), 
    ('group9','TRIGGER_EXCEPTIONS','Y','INSERT_TS','',''), 
    ('group9','USER_PARA_FORM_PARA_VER','N','LAST_MOD_TS','','CFK_FORM_PARAGRAPH_VERSION_GID'), 
    ('group9','USER_SESSION','N','LAST_MOD_TS','','USER_SESSION_GID'), 
    ('group9','WORK_ITEM','Y','LAST_MOD_TS','','WORK_ITEM_GID'), 
    ('group9','WORK_ITEM_H','Y','LAST_MOD_TS','','WORK_ITEM_GID'), 
    ('group9','WORK_ITEM_RELATIONSHIP','N','LAST_MOD_TS','','FK_PARENT_WORK_ITEM_GID'), 
    ('group9','WORK_ITEM_RELATIONSHIP_H','Y','LAST_MOD_TS','L','FK_PARENT_WORK_ITEM_GID'),#reset back
    ('group9','WORK_ITEM_REQUEST','N','LAST_MOD_TS','','FK_WORK_ITEM_GID'), 
    ('group9','WORK_ITEM_REQUEST_EMPLOYEE','N','LAST_MOD_TS','','FK_WORK_ITEM_GID'), 
    ('group9','WORKER_FOLDER','N','LAST_MOD_TS','','WORKER_FOLDER_ID'), 
    ('group9','WORKER_FOLDER_ITEM','Y','LAST_MOD_TS','','FK_WORKER_FOLDER_ID'), 
    ('group9','WRITING_REVIEW','N','LAST_MOD_TS','','WRITING_REVIEW_ID'), 
    ('group9','TM_STATES','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group9','TM_APPEALS','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'), 
    ('group9','TM_ELECTRONIC_ADDR_H','Y','LAST_MOD_TS','','FK_ELECTRONIC_ADDRESS_GID'), 
]

# COMMAND ----------

tmngpdb_metadata_group10 = [
    ('group10','TM_FILINGS','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_FILING_BASES','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_ITU_EXTENSION','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_ITU_EXTENSION_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_ITU_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_OG_PUBLICATIONS','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'), 
    ('group10','TM_OG_PUBLICATIONS_H','Y','LAST_MOD_TS','','CFK_TRADEMARK_GID'), 
    ('group10','TM_CLASS_REFERENCE_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_GROUP','N','LAST_MOD_TS','','TM_GROUP_ID'), 
    ('group10','TM_GROUP_ITEM','Y','LAST_MOD_TS','','FK_TM_GROUP_ID, FK_TRADEMARK_GID'), 
    ('group10','TM_LITERAL_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_LOCATIONS_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), #reset back
    ('group10','TM_MAILING_ADDR_H','Y','LAST_MOD_TS','','FK_MAILING_ADDRESS_GID'), 
    ('group10','TM_MARK_TYPE','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_MARK_TYPE_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_NOTIFICATION_MESSAGE','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_ORGANIZATION_LOCATION','Y','LAST_MOD_TS','','LOCATION_ID'), 
    ('group10','TM_PHYSICAL_LOCATION','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_POST_REGISTRATION','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_PROCEEDING','Y','LAST_MOD_TS','','TM_PROCEEDING_ID'), 
    ('group10','TM_PROCEEDING_H','Y','LAST_MOD_TS','','TM_PROCEEDING_ID'), 
    ('group10','TM_PSEUDO_CLASS','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_PSEUDO_CLASS_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_PSEUDO_MARK','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_DESIGN_ELEMENT_H','Y','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_FOREIGN_BASIS','N','LAST_MOD_TS','','FK_TRADEMARK_GID'), 
    ('group10','TM_PRIOR_REGISTRATION','N','LAST_MOD_TS','','FK_TRADEMARK_GID'),
    # ('group10','TRAM_CL','N','','',''),
    # ('group10','TRAM_CM','N','','','CM_RSN'),
    # ('group10','TRAM_MC','N','','','mc_dt_mega'),
    ('group10','STND_FSM_TYPE_EVENT','N','LAST_MOD_TS','','FSM_TYPE_EVENT_ID'), 
    ('group10','STND_FSM_TYPE_STATE','N','LAST_MOD_TS','','FSM_TYPE_STATE_ID'), 
    ('group10','STND_FSM_TYPE_STATE_RULE','Y','LAST_MOD_TS','','FSM_TYPE_STATE_RULE_ID'), 
    ('group10','STND_LEGACY_STATUS','N','LAST_MOD_TS','','STATUS_NO'), 
    ('group10','STND_OFFICE_ACTION_CT_STATE','Y','LAST_MOD_TS','','CFK_FSM_TYPE_STATE_ID, FK_OFFICE_ACTION_CATEGORY_CD'), 
    ('group10','STND_OFFICE_ACTN_RULE_ITM','N','LAST_MOD_TS','','OFFICE_ACTN_RULE_ITM_ID'),  
]

# COMMAND ----------

tmngpdb_metadata_group12 = [
    ('group12','SEARCH_STRATEGY','Y','LAST_MOD_TS','','SEARCH_STRATEGY_ID'),
]

# COMMAND ----------

tmbuscalendar_metadata = [
    ('weekly_load','BUSINESS_CALENDAR_RANGE','N','LAST_MOD_TS','','RANGE_NM'),
    ('weekly_load','BUSINESS_CALENDAR_DAY','N','LAST_MOD_TS','',''),
    ('weekly_load','BUS_CALENDAR_DAY_PROPERTY','N','LAST_MOD_TS','','CFK_PROPERTY_TYPE_CD')
]

# COMMAND ----------

tmintltm_metadata = [
    ('daily_load','INTERNATIONAL_APPL_EVENT','Y','LAST_MOD_TS','','fk_international_appl_gid'),
    ('daily_load','BASE_APPLICATION','N','LAST_MOD_TS','','FK_INTERNATIONAL_APPL_GID'),
    ('daily_load','BASE_APPLICATION_H','N','LAST_MOD_TS','','FK_INTERNATIONAL_APPL_GID'),
    ('daily_load','INTERNATIONAL_APPLICATION','N','LAST_MOD_TS','','INTERNATIONAL_APPLICATION_GID'),
    ('daily_load','INTERNATIONAL_APPLICATION_H','N','LAST_MOD_TS','','INTERNATIONAL_APPLICATION_GID'),
    ('daily_load','INTERNATIONAL_REGISTRATION','N','LAST_MOD_TS','','INTERNATIONAL_REG_GID'),
    ('daily_load','INTERNATIONAL_REGISTRATION_H','N','LAST_MOD_TS','','INTERNATIONAL_REG_GID'),
    ('daily_load','INTERNATIONAL_REG_TM','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('daily_load','INTERNATIONAL_REG_TM_H','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('daily_load','INTERNATIONAL_TM','N','LAST_MOD_TS','','INTERNATIONAL_REG_NO'),
    ('daily_load','INTERNATIONAL_TM_H','N','LAST_MOD_TS','','CFK_TRANSACTION_INSTANCE_GID'),
    ('weekly_load','INTERNATIONAL_APPL_EVNT_RSN','Y','LAST_MOD_TS','','international_appl_evnt_rsn_id'),
    ('daily_load','BASE_APPL_INTL_REG','Y','LAST_MOD_TS','','FK_INTERNATIONAL_APPL_GID'),
    ('daily_load','INTERNATIONAL_REG_TM_NOTICE','N','LAST_MOD_TS','',''),
    ('daily_load','TM_BASE_APPLICATION_NOTICE','N','LAST_MOD_TS','','')
]

# COMMAND ----------

tmngfpepp_metadata = [
('weekly_load','DATABASECHANGELOG','Y','','',''),
('daily_load','FORM_PARAGRAPH_REASON','Y','','',''),
('daily_load','DATABASECHANGELOGLOCK','N','','','ID'),
('weekly_load','QRTZ_BLOB_TRIGGERS','N','','','TRIGGER_NAME'),
('weekly_load','QRTZ_CALENDARS','N','','','CALENDAR_NAME'),
('daily_load','QRTZ_CRON_TRIGGERS','N','','','TRIGGER_NAME'),
('weekly_load','QRTZ_FIRED_TRIGGERS','N','','','ENTRY_ID'),
('weekly_load','QRTZ_JOB_DETAILS','N','','','SCHED_NAME'),
('daily_load','QRTZ_LOCKS','Y','','','LOCK_NAME'),
('weekly_load','QRTZ_PAUSED_TRIGGER_GRPS','Y','','','SCHED_NAME'),
('daily_load','QRTZ_SCHEDULER_STATE','N','','','SCHED_NAME'),
('weekly_load','QRTZ_SIMPLE_TRIGGERS','N','','','TRIGGER_NAME'),
('weekly_load','QRTZ_SIMPROP_TRIGGERS','N','','','TRIGGER_NAME'),
('daily_load','QRTZ_TRIGGERS','N','','','TRIGGER_NAME'),
('daily_load','FORM_PARAGRAPH','Y','LAST_MOD_TS','','FORM_PARAGRAPH_GID'),
('daily_load','FORM_PARAGRAPH_ACTION','N','LAST_MOD_TS','','FORM_PARAGRAPH_ACTION_GID'),
('daily_load','FORM_PARAGRAPH_VERSION','Y','LAST_MOD_TS','','FORM_PARAGRAPH_VERSION_GID'),
('weekly_load','FPV_SCHEDULED_JOB','N','LAST_MOD_TS','','FK_FORM_PARAGRAPH_VERSION_GID'),
('daily_load','STND_CHAPTER_SECTION','N','LAST_MOD_TS','','CHAPTER_SECTION_ID'),
('weekly_load','STND_FORM_PARAGRAPH_ACTION','N','LAST_MOD_TS','','FORM_PARAGRAPH_ACTION_CD'),
('weekly_load','STND_FORM_PARAGRAPH_CATEGORY','N','LAST_MOD_TS','','FORM_PARAGRAPH_CATEGORY_ID'),
('weekly_load','STND_FORM_PARAGRAPH_GROUP','N','LAST_MOD_TS','','FORM_PARAGRAPH_GROUP_ID'),
('daily_load','STND_FORM_PARAGRAPH_REASON','N','LAST_MOD_TS','','FORM_PARAGRAPH_REASON_ID'),
]

# COMMAND ----------

# MAGIC %md
# MAGIC databridge_metadata = [
# MAGIC ('cdc_load_tables','mhi','N',''),
# MAGIC ('cdc_load_tables','em','N',''),
# MAGIC ('cdc_load_tables','mas','N',''),
# MAGIC ('cdc_load_tables','mif','N',''),
# MAGIC ('cdc_load_tables','tt','N',''),
# MAGIC ('cdc_load_tables','cm','N',''),
# MAGIC ]

# COMMAND ----------

eogadmin_metadata = [
('weekly_load','fsm_instance','N','last_mod_ts','','fsm_instance_id'),
('weekly_load','fsm_instance_h','N','last_mod_ts','','fsm_instance_h_id'),
('weekly_load','fsm_interlock','N','last_mod_ts','','fsm_interlock_id'),
('weekly_load','og_appeal_fsm_instance','N','last_mod_ts','','cfk_root_fsm_instance_id'),
('weekly_load','og_review_fsm_instance','N','last_mod_ts','','cfk_current_fsm_instance_id'),
('weekly_load','og_review_query_fsm_instance','N','last_mod_ts','','cfk_current_fsm_instance_id'),
('weekly_load','qrtz_blob_triggers','N','','','sched_name'),
('weekly_load','qrtz_calendars','N','','','sched_name'),
('weekly_load','qrtz_cron_triggers','N','','','sched_name'),
('weekly_load','qrtz_fired_triggers','N','','','sched_name'),
('weekly_load','qrtz_job_details','N','','','sched_name'),
('weekly_load','qrtz_locks','Y','','','sched_name'),
('weekly_load','qrtz_paused_trigger_grps','Y','','','sched_name'),
('weekly_load','qrtz_scheduler_state','N','','','sched_name'),
('weekly_load','qrtz_simple_triggers','N','','','sched_name'),
('weekly_load','qrtz_simprop_triggers','N','','','sched_name'),
('weekly_load','qrtz_triggers','N','','','sched_name'),
('weekly_load','stnd_domain','N','last_mod_ts','','domain_cd'),
('weekly_load','stnd_fsm_category','N','last_mod_ts','','fsm_category_cd'),
('weekly_load','stnd_fsm_interlock','Y','last_mod_ts','','fsm_interlock_id'),
('weekly_load','stnd_fsm_interlock_type','N','last_mod_ts','','fsm_interlock_type_cd'),
('weekly_load','stnd_fsm_type','N','last_mod_ts','','fsm_type_id'),
('weekly_load','stnd_fsm_type_event','N','last_mod_ts','','fsm_type_event_id'),
('weekly_load','stnd_fsm_type_state','N','last_mod_ts','','fsm_type_state_id'),
('weekly_load','stnd_fsm_type_state_rule','N','last_mod_ts','','fsm_type_state_rule_id'),
('weekly_load','stnd_interlock_type','Y','last_mod_ts','','stnd_interlock_type_cd'),
('weekly_load','user_profile','N','last_mod_ts','','user_profile_id'),
('weekly_load','user_profile_preference','N','last_mod_ts','','fk_user_profile_id'),
]

# COMMAND ----------

jbteasps_metadata = [
    ('weekly_load','stnd_source_system','N','','','source_system_id'),
    ('daily_load','audit_log','N','','','audit_log_id, serial_no'),
    ('weekly_load','stnd_transaction_type','N','','','transaction_type_cd'),
    ("daily_load", "interested_party", "N", "", "", "cfk_patron_id"),
    ("daily_load", "sponsorship", "N", "", "", "sponsorship_id"),
    ("daily_load", "sponsorship_h", "N", "", "", "sponsorship_id"),
    ("weekly_load", "stnd_form", "N", "", "", "form_cd"),
    ("weekly_load", "stnd_proof_type", "N", "", "", "proof_cd"),
    ("weekly_load", "stnd_signature_type", "N", "", "", "signature_type_cd"),
    ("weekly_load", "stnd_sponsorship_status", "N", "", "", "sponsorship_status_id"),
]

# COMMAND ----------

proceeding_metadata = [
    ('daily_load','petition','N','','','FK_PROCEEDING_GID'),
    ('weekly_load','petition_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','petition_response','N','','','FK_PROCEEDING_GID'),
    ('daily_load','petition_response_document','N','','','FK_PROCEEDING_GID'),
    ('weekly_load','petition_response_document_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','petition_response_h','N','','','FK_PROCEEDING_GID'),
    ('weekly_load','prcdng_trigger_exceptions','Y','','',''),
    ('daily_load','proceeding','N','','','PROCEEDING_GID'),
    ('daily_load','proceeding_class','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_class_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_document','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_document_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_event','N','','','PROCEEDING_EVENT_ID'),
    ('weekly_load','proceeding_event_reason','N','','','PROCEEDING_EVENT_REASON_ID'),
    ('daily_load','proceeding_fee','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_fee_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_h','N','','','PROCEEDING_GID'),
    ('daily_load','proceeding_mark','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_mark_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_participant','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_participant_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_statement','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_statement_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','proceeding_tran_instance', 'N','','','PROCEEDING_TRAN_INSTNC_GID'),
    ('daily_load','sync_tm_com_exception','N','','','TM_COM_EXCEPTION_ID'),
    #('daily_load','tram_pi','N','','',''),
    ('daily_load','letter_of_protest','N','','','FK_PROCEEDING_GID'),
    ('daily_load','letter_of_protest_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','lop_legal_basis','N','','','FK_PROCEEDING_GID'),
    ('daily_load','lop_legal_basis_h','N','','','FK_PROCEEDING_GID'),
    ('daily_load','lop_legal_basis_trademark','N','','','LOP_LEGAL_BASIS_TRADEMARK_ID'),
    ('daily_load','lop_legal_basis_trademark_h','N','','','CFK_TRANSACTION_INSTANCE_GID'),
    ('weekly_load','proceeding_intl_appl','N','','','FK_PROCEEDING_GID'),
    ('weekly_load','proceeding_intl_appl_h','N','','','FK_PROCEEDING_GID'),
    #('daily_load','proceeding_statement_bkp','N','','',''),
    #('daily_load','proceeding_statement_h_bkp','N','','',''),
    ('weekly_load','stnd_lop_legal_basis','N','','','LOP_LEGAL_BASIS_CD'),
    ('weekly_load','stnd_petition_to_director','N','','','PETITION_TO_DIRECTOR_CD'),
    #('daily_load','sync_tm_com_exception_old','N','','',''),
    #('daily_load','temp_lop_cntl','N','','',''),
]

# COMMAND ----------

tmprodvty_metadata = tmprodvty_metadata = [
    ('daily_load','production_transaction','N','last_mod_ts','','cfk_object_gid'),
    ('weekly_load','productivity_action','N','last_mod_ts','','productivity_action_id'),
    ('weekly_load','worker_time_entry','N','last_mod_ts','','cfk_worker_gid'),
    ('daily_load','PRODUCTION_TRANSACTION_ERRLOG','Y','LAST_MOD_TS','','CFK_OBJECT_GID')
]


# COMMAND ----------

tmreviews_metadata = [
    ('daily_load','PRE_EXAM_QUALITY_REVIEW','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('daily_load','PRE_EXAM_QUALITY_RVW_ERR','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('daily_load','POST_REG_QUALITY_REVIEW','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('weekly_load','POST_REG_QUALITY_REVIEW_ERRLOG','Y','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('daily_load','POST_REG_QUALITY_REVIEW_H','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
    ('weekly_load','POST_REG_REVIEW_NOTICE','N','LAST_MOD_TS','','CFK_BCR_PAY_PERIOD_RANGE_NAME'),
    ('daily_load','POST_REG_REVIEW_NOTICE_ERRLOG','Y','LAST_MOD_TS','','ORA_ERR_MESG$,CFK_TRADEMARK_GID'),
    ('weekly_load','POST_REG_REVIEW_NOTICE_H','N','LAST_MOD_TS','','CFK_BCR_PAY_PERIOD_RANGE_NAME,DN_SERIAL_NUM_TX'), 
    ('daily_load','PREG_QUALITY_REVIEW_ELEMENT','N','LAST_MOD_TS','','CFK_TRADEMARK_GID,FK_PRQR_CREATED_DT'),
    ('weekly_load','PREG_QUALITY_REVIEW_ELEMENT_ERRLOG','Y','LAST_MOD_TS','','ORA_ERR_MESG$,CFK_TRADEMARK_GID'),
    ('daily_load','PREG_QUALITY_REVIEW_ELEMENT_H','N','LAST_MOD_TS','','CFK_TRADEMARK_GID'),
]

# COMMAND ----------

tmworker_metadata = [
    ('daily_load','TM_ORGANIZATION','N','LAST_MOD_TS','','TM_ORGANIZATION_GID'),
    ('daily_load','WORKER','N','LAST_MOD_TS','','WORKER_GID'),
    ('daily_load','TM_ORGANIZATION_RLTNSHP','N','LAST_MOD_TS','','FK_CHILD_TM_ORGANIZATION_GID, FK_PARENT_TM_ORGANIZATION_GID'),
    ('daily_load','TRANSACTION_INSTANCE','N','LAST_MOD_TS','','TRANSACTION_INSTANCE_GID'),
    ('weekly_load','USER_ROLE','N','LAST_MOD_TS','','USER_ROLE_ID'),#
    ('weekly_load','USER_ROLE_GROUP','N','LAST_MOD_TS','','USER_ROLE_GROUP_CD'),#
    ('weekly_load','WORKER_H','N','LAST_MOD_TS','','WORKER_GID'),#
    ('daily_load','WORKER_ROLE_H','N','LAST_MOD_TS','','FK_USER_ROLE_ID'),#
    ('weekly_load','WORKER_ROLE','N','LAST_MOD_TS','','FK_USER_ROLE_ID'),
    ('daily_load','SYNC_TRANSLATE_LOCATION','Y','','','')
]

# COMMAND ----------

tmngidmp_metadata = [
    ('daily_load', 'audit_revision', 'N','LAST_MOD_TS','','AUDIT_REVISION_ID'),
    ('daily_load', 'goods_services_term', 'N', 'LAST_MOD_TS','','GOODS_SERVICES_TERM_ID'),
    ('daily_load', 'goods_services_term_draft', 'N', 'LAST_MOD_TS','','GOODS_SERVICES_TERM_ID,GOODS_SERVICES_TERM_ID_TX'),
    ('daily_load', 'goods_services_term_note', 'Y', 'LAST_MOD_TS','','FK_GOODS_SERVICES_TERM_ID'),
    ('daily_load', 'goods_services_term_note_draft', 'N', 'LAST_MOD_TS','','FK_GOODS_SERVICES_TERM_ID'),
    ('daily_load', 'stnd_application_property', 'N', 'LAST_MOD_TS','','APPLICATION_PROPERTY_CD'),
    #('cdc_load_tables', 'audit_revision', 'N','LAST_MOD_TS'),
    ('weekly_load','data_comp', 'Y', '','','SN'),
    ('weekly_load','data_comp_parsed', 'Y', '','','SN,ORG_TXT'),
    ('weekly_load','data_comp_result', 'Y', '','','SERIAL_NUMBER'),
    ('weekly_load','data_comp_sam', 'Y', '','','SN,TXT'),
    ('weekly_load','data_comp_sam_result', 'Y', '','','SERIAL_NUMBER,CLASS'),
    ('weekly_load','data_comp_test', 'Y', '','','SN,TXT'),
    ('weekly_load','data_id', 'Y', '','','CLS'),
    ('weekly_load','data_id_case_level_result', 'Y', '','','SERIAL_NUMBER'),
    ('weekly_load','data_id_parsed', 'Y', '','','CLS'),
    ('weekly_load','data_id_parsed_standard', 'Y', '','','CLS'),
    ('weekly_load','data_teas_plus_clob', 'Y', '','','SERIALNUMBER,CLASS'),
    ('weekly_load','data_teas_standard_clob', 'Y', '','','SERIALNUMBER,SUBMISSIONID'),
    #('cdc_load_tables', 'goods_services_term', 'N', 'LAST_MOD_TS','',''),
    #('cdc_load_tables', 'goods_services_term_draft', 'N', 'LAST_MOD_TS','',''),
    #('cdc_load_tables', 'goods_services_term_note', 'Y', 'LAST_MOD_TS','',''),
    #('cdc_load_tables', 'goods_services_term_note_draft', 'N', 'LAST_MOD_TS','',''),
    ('weekly_load', 'international_class_version', 'N', 'LAST_MOD_TS','','FK_CLASS_ID'),
    ('weekly_load', 'international_clsfcn_edn', 'N', 'LAST_MOD_TS','','EDITION_NO'),
    ('weekly_load', 'intl_clsfcn_edn_ver', 'N', 'LAST_MOD_TS','','FK_EDITION_NO,VERSION_YEAR_NO'),
    ('weekly_load', 'intl_clsfcn_edn_ver_rel', 'N', 'LAST_MOD_TS','','FK_EDITION_NO'),
    ('weekly_load', 'menu_item', 'N', 'LAST_MOD_TS','','MENU_ITEM_ID'),
    ('weekly_load', 'stnd_application_message', 'Y', 'LAST_MOD_TS','','APPLICATION_MESSAGE_ID'),
    #('cdc_load_tables', 'stnd_application_property', 'N', 'LAST_MOD_TS','',''),
    ('weekly_load', 'stnd_class', 'N', 'LAST_MOD_TS','','CLASS_NO,CLASS_ID'),
    ('weekly_load', 'stnd_class_schedule', 'N', 'LAST_MOD_TS','','CLASS_SCHEDULE_CD'),
    ('weekly_load', 'stnd_coordinated_class', 'N', 'LAST_MOD_TS','','FK_CLASS_ID'),
    ('weekly_load', 'stnd_goods_services_note', 'N', 'LAST_MOD_TS','','GOODS_SERVICES_NOTE_CD'),
    ('weekly_load', 'stnd_synonym_group', 'Y', 'LAST_MOD_TS','','SYNONYM_GROUP_ID'),
    ('weekly_load', 'stnd_term_status', 'N', 'LAST_MOD_TS','','TERM_STATUS_CD'),
    ('weekly_load', 'stnd_us_intl_cls_mapping', 'N', 'LAST_MOD_TS','','FK_US_CLASS_ID'),
    ('weekly_load', 'sync_idm_update_log', 'Y', '','','INSERT_TS'),
    ('weekly_load', 'taxonomy_group', 'N', 'LAST_MOD_TS','','TAXONOMY_GROUP_ID'),
    ('weekly_load', 'tm5_file', 'N', 'LAST_MOD_TS','','TM5_FILE_ID'),
    ('weekly_load', 'tm5_goods_services', 'N', 'LAST_MOD_TS','','FK_TM5_FILE_ID')
]

# COMMAND ----------

efoiap_metadata = [
    ('weekly_load','appeal_decision_issue','N','','','FK_SEQUENCE_NO, FK_TRADEMARK_PROCEEDING_NO, LEVEL_1_ISSUE_CD'),
    ('weekly_load','document_type','N','','',''),
    ('weekly_load','stnd_decision','N','','',''),
    ('weekly_load','stnd_level_1_issue','N','','',''),
    ('weekly_load','stnd_level_2_issue','N','','','FK_LEVEL_1_ISSUE_CD, LEVEL_2_ISSUE_CD'),
    ('daily_load','tm_appeal_decision','N','','','TM_APPEAL_DECISION_ID'),
    ('daily_load','tm_appeal_decision_h','N','','','TM_APPEAL_DECISION_H_ID'),
    ('daily_load','trademark_appeal_decision','N','','','SEQUENCE_NO, TRADEMARK_PROCEEDING_NO'),
    ('weekly_load','efoia_trigger_exceptions','Y','','',''),
    ('weekly_load','prosecution_history_event','Y','','','fk_proceedingnumber0'),
    ('daily_load','prosecution_history_event2','Y','','','fk_proceedingnumber0'),
    ('weekly_load','tmng_go_live','Y','','',''),
    #('cdc_load_tables','tm_appeal_decision_errlog','Y','','',''),
]

# COMMAND ----------

tmrefdata_metadata = [
    ('daily_load', 'CODE_TYPE', 'Y', '','','CODE_TYPE_ID'),
    ('daily_load', 'CODE_TYPE_62623', 'Y', '','',''),
    ('daily_load', 'CODE_TYPE_DEPENDENCY', 'Y', '','','FK_DEPENDENT_CODE_TYPE_ID, FK_ENABLING_CODE_TYPE_ID'),
    ('daily_load', 'CODE_TYPE_DEPENDENCY_62623', 'Y', '','',''),
    ('daily_load', 'CODE_TYPE_DOMAIN_SERVICE', 'Y', '','','FK_CODE_TYPE_ID, FK_DOMAIN_SERVICE_ID'),
    ('daily_load', 'CODE_TYPE_PROPERTY_TYPE', 'Y', '','','PROPERTY_TYPE_ID'),
    ('daily_load', 'CODE_TYPE_PROPERTY_TYPE_62623', 'Y', '','',''),
    ('daily_load', 'CODE_VALUE', 'Y', '','','CODE_VALUE_ID'),
    ('daily_load', 'CODE_VALUE_62623', 'Y', '','',''),
    ('daily_load', 'CODE_VALUE_BAK', 'Y', '','',''),
    ('daily_load', 'CODE_VALUE_DEPENDENCY', 'Y', '','','FK_CHILD_CODE_VALUE_ID, FK_PARENT_CODE_VALUE_ID'),
    ('daily_load', 'CODE_VALUE_DEPENDENCY_62623', 'Y', '','',''),
    ('daily_load', 'CODE_VALUE_PROPERTY', 'Y', '','','FK_CODE_VALUE_ID, FK_PROPERTY_TYPE_ID'),
    ('daily_load', 'CODE_VALUE_PROPERTY_62623', 'Y', '','',''),
    ('daily_load', 'DOMAIN_SERVICE', 'Y', '','','DOMAIN_SERVICE_ID'),
    ('daily_load', 'DOMAIN_SERVICE_COMPLETE_LIST', 'Y', '','','')
]
